/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.api;

import com.sdk.treezor.model.DefaultError;
import com.sdk.treezor.model.GetBalances200Response;
import com.sdk.treezor.model.GetWalletBalanceHistory200ResponseValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for BalancesApi
 */
@Disabled
public class BalancesApiTest {

    private final BalancesApi api = new BalancesApi();

    
    /**
     * Search Balances
     *
     * Retrieve Balances for a given &#x60;walletId&#x60; or &#x60;userId&#x60;.
     */
    @Test
    public void getBalancesTest()  {
        // uncomment below to test the function
        //String accessTag = null;
        //Integer walletId = null;
        //Integer userId = null;
        //GetBalances200Response response = api.getBalances(accessTag, walletId, userId).block();

        // TODO: test validations
    }
    
    /**
     * Get Wallet Balance history
     *
     * Retrieve the Balance History of a Wallet.
     */
    @Test
    public void getWalletBalanceHistoryTest()  {
        // uncomment below to test the function
        //Integer walletId = null;
        //String dateFrom = null;
        //String dateTo = null;
        //Map<String, GetWalletBalanceHistory200ResponseValue> response = api.getWalletBalanceHistory(walletId, dateFrom, dateTo).block();

        // TODO: test validations
    }
    
}
