/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.api;

import com.sdk.treezor.model.DefaultError;
import com.sdk.treezor.model.GetPayinrefund200Response;
import com.sdk.treezor.model.GetPayinrefunds200Response;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for PayinRefundsApi
 */
@Disabled
public class PayinRefundsApiTest {

    private final PayinRefundsApi api = new PayinRefundsApi();

    
    /**
     * Get Payin Refund
     *
     * Get a payin refund.
     */
    @Test
    public void getPayinrefundTest()  {
        // uncomment below to test the function
        //Long id = null;
        //GetPayinrefund200Response response = api.getPayinrefund(id).block();

        // TODO: test validations
    }
    
    /**
     * Search Payin Refunds
     *
     * Search for payin refunds. These can relate to [Acquiring](/guide/acquiring/legacy-v1.html#refunds) or [SEPA recalls](/guide/transfers/sepa-recalls.html). 
     */
    @Test
    public void getPayinrefundsTest()  {
        // uncomment below to test the function
        //String accessTag = null;
        //Integer payinId = null;
        //Integer payinrefundId = null;
        //String payinrefundTag = null;
        //String payinrefundStatus = null;
        //Integer walletId = null;
        //String payinrefundDate = null;
        //Integer userId = null;
        //String amount = null;
        //String currency = null;
        //Integer pageNumber = null;
        //String cursor = null;
        //Integer pageCount = null;
        //String sortBy = null;
        //String sortOrder = null;
        //OffsetDateTime createdDateFrom = null;
        //OffsetDateTime createdDateTo = null;
        //OffsetDateTime updatedDateFrom = null;
        //OffsetDateTime updatedDateTo = null;
        //GetPayinrefunds200Response response = api.getPayinrefunds(accessTag, payinId, payinrefundId, payinrefundTag, payinrefundStatus, walletId, payinrefundDate, userId, amount, currency, pageNumber, cursor, pageCount, sortBy, sortOrder, createdDateFrom, createdDateTo, updatedDateFrom, updatedDateTo).block();

        // TODO: test validations
    }
    
}
