/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DigitalizedCardsGetDigitalizedCardResponse
 */
class DigitalizedCardsGetDigitalizedCardResponseTest {
    private final DigitalizedCardsGetDigitalizedCardResponse model = new DigitalizedCardsGetDigitalizedCardResponse();

    /**
     * Model tests for DigitalizedCardsGetDigitalizedCardResponse
     */
    @Test
    void testDigitalizedCardsGetDigitalizedCardResponse() {
        // TODO: test DigitalizedCardsGetDigitalizedCardResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'cardId'
     */
    @Test
    void cardIdTest() {
        // TODO: test cardId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'walletProvider'
     */
    @Test
    void walletProviderTest() {
        // TODO: test walletProvider
    }

    /**
     * Test the property 'tokenUniqueReference'
     */
    @Test
    void tokenUniqueReferenceTest() {
        // TODO: test tokenUniqueReference
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'deviceType'
     */
    @Test
    void deviceTypeTest() {
        // TODO: test deviceType
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'deviceName'
     */
    @Test
    void deviceNameTest() {
        // TODO: test deviceName
    }

    /**
     * Test the property 'activationMethod'
     */
    @Test
    void activationMethodTest() {
        // TODO: test activationMethod
    }

    /**
     * Test the property 'tokenServiceProvider'
     */
    @Test
    void tokenServiceProviderTest() {
        // TODO: test tokenServiceProvider
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    void modifiedDateTest() {
        // TODO: test modifiedDate
    }

}
