/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPayinrefund200ResponsePayinrefundsInner
 */
class GetPayinrefund200ResponsePayinrefundsInnerTest {
    private final GetPayinrefund200ResponsePayinrefundsInner model = new GetPayinrefund200ResponsePayinrefundsInner();

    /**
     * Model tests for GetPayinrefund200ResponsePayinrefundsInner
     */
    @Test
    void testGetPayinrefund200ResponsePayinrefundsInner() {
        // TODO: test GetPayinrefund200ResponsePayinrefundsInner
    }

    /**
     * Test the property 'payinrefundId'
     */
    @Test
    void payinrefundIdTest() {
        // TODO: test payinrefundId
    }

    /**
     * Test the property 'payinrefundTag'
     */
    @Test
    void payinrefundTagTest() {
        // TODO: test payinrefundTag
    }

    /**
     * Test the property 'payinrefundStatus'
     */
    @Test
    void payinrefundStatusTest() {
        // TODO: test payinrefundStatus
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'payinId'
     */
    @Test
    void payinIdTest() {
        // TODO: test payinId
    }

    /**
     * Test the property 'payinrefundDate'
     */
    @Test
    void payinrefundDateTest() {
        // TODO: test payinrefundDate
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'totalRows'
     */
    @Test
    void totalRowsTest() {
        // TODO: test totalRows
    }

}
