/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetRecallSctInst200ResponseRecallsInner
 */
class GetRecallSctInst200ResponseRecallsInnerTest {
    private final GetRecallSctInst200ResponseRecallsInner model = new GetRecallSctInst200ResponseRecallsInner();

    /**
     * Model tests for GetRecallSctInst200ResponseRecallsInner
     */
    @Test
    void testGetRecallSctInst200ResponseRecallsInner() {
        // TODO: test GetRecallSctInst200ResponseRecallsInner
    }

    /**
     * Test the property 'recallId'
     */
    @Test
    void recallIdTest() {
        // TODO: test recallId
    }

    /**
     * Test the property 'creationDateTIme'
     */
    @Test
    void creationDateTImeTest() {
        // TODO: test creationDateTIme
    }

    /**
     * Test the property 'statusLabel'
     */
    @Test
    void statusLabelTest() {
        // TODO: test statusLabel
    }

    /**
     * Test the property 'cxlId'
     */
    @Test
    void cxlIdTest() {
        // TODO: test cxlId
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'additionalInformation'
     */
    @Test
    void additionalInformationTest() {
        // TODO: test additionalInformation
    }

    /**
     * Test the property 'sctrDbtrIBAN'
     */
    @Test
    void sctrDbtrIBANTest() {
        // TODO: test sctrDbtrIBAN
    }

    /**
     * Test the property 'sctrDbtrBIC'
     */
    @Test
    void sctrDbtrBICTest() {
        // TODO: test sctrDbtrBIC
    }

    /**
     * Test the property 'sctrDbtrName'
     */
    @Test
    void sctrDbtrNameTest() {
        // TODO: test sctrDbtrName
    }

    /**
     * Test the property 'sctrDbtrAddress'
     */
    @Test
    void sctrDbtrAddressTest() {
        // TODO: test sctrDbtrAddress
    }

    /**
     * Test the property 'sctrDbtrCountry'
     */
    @Test
    void sctrDbtrCountryTest() {
        // TODO: test sctrDbtrCountry
    }

    /**
     * Test the property 'sctrCdtrIBAN'
     */
    @Test
    void sctrCdtrIBANTest() {
        // TODO: test sctrCdtrIBAN
    }

    /**
     * Test the property 'sctrCdtrBIC'
     */
    @Test
    void sctrCdtrBICTest() {
        // TODO: test sctrCdtrBIC
    }

    /**
     * Test the property 'sctrCdtrName'
     */
    @Test
    void sctrCdtrNameTest() {
        // TODO: test sctrCdtrName
    }

    /**
     * Test the property 'sctrCdtrAddress'
     */
    @Test
    void sctrCdtrAddressTest() {
        // TODO: test sctrCdtrAddress
    }

    /**
     * Test the property 'sctrCdtrCountry'
     */
    @Test
    void sctrCdtrCountryTest() {
        // TODO: test sctrCdtrCountry
    }

    /**
     * Test the property 'sctrMsgId'
     */
    @Test
    void sctrMsgIdTest() {
        // TODO: test sctrMsgId
    }

    /**
     * Test the property 'sctrInstrId'
     */
    @Test
    void sctrInstrIdTest() {
        // TODO: test sctrInstrId
    }

    /**
     * Test the property 'sctrTxId'
     */
    @Test
    void sctrTxIdTest() {
        // TODO: test sctrTxId
    }

    /**
     * Test the property 'sctrE2EID'
     */
    @Test
    void sctrE2EIDTest() {
        // TODO: test sctrE2EID
    }

    /**
     * Test the property 'sctrAmount'
     */
    @Test
    void sctrAmountTest() {
        // TODO: test sctrAmount
    }

    /**
     * Test the property 'sctrSettlementDate'
     */
    @Test
    void sctrSettlementDateTest() {
        // TODO: test sctrSettlementDate
    }

    /**
     * Test the property 'sctrRemittanceInformation'
     */
    @Test
    void sctrRemittanceInformationTest() {
        // TODO: test sctrRemittanceInformation
    }

    /**
     * Test the property 'sctrTrzId'
     */
    @Test
    void sctrTrzIdTest() {
        // TODO: test sctrTrzId
    }

    /**
     * Test the property 'sctrExternalId'
     */
    @Test
    void sctrExternalIdTest() {
        // TODO: test sctrExternalId
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'receivedDate'
     */
    @Test
    void receivedDateTest() {
        // TODO: test receivedDate
    }

    /**
     * Test the property 'payinRefundId'
     */
    @Test
    void payinRefundIdTest() {
        // TODO: test payinRefundId
    }

    /**
     * Test the property 'payinRefundUuid'
     */
    @Test
    void payinRefundUuidTest() {
        // TODO: test payinRefundUuid
    }

    /**
     * Test the property 'responseType'
     */
    @Test
    void responseTypeTest() {
        // TODO: test responseType
    }

    /**
     * Test the property 'negativeResponseReasonCode'
     */
    @Test
    void negativeResponseReasonCodeTest() {
        // TODO: test negativeResponseReasonCode
    }

    /**
     * Test the property 'negativeResponseAdditionalInformation'
     */
    @Test
    void negativeResponseAdditionalInformationTest() {
        // TODO: test negativeResponseAdditionalInformation
    }

    /**
     * Test the property 'responseComment'
     */
    @Test
    void responseCommentTest() {
        // TODO: test responseComment
    }

    /**
     * Test the property 'automaticResponse'
     */
    @Test
    void automaticResponseTest() {
        // TODO: test automaticResponse
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    void updatedDateTest() {
        // TODO: test updatedDate
    }

}
