/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.PutLimitsRequestRestrictionGroupLimits;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PutLimitsRequest
 */
class PutLimitsRequestTest {
    private final PutLimitsRequest model = new PutLimitsRequest();

    /**
     * Model tests for PutLimitsRequest
     */
    @Test
    void testPutLimitsRequest() {
        // TODO: test PutLimitsRequest
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'accessTag'
     */
    @Test
    void accessTagTest() {
        // TODO: test accessTag
    }

    /**
     * Test the property 'limitAtmYear'
     */
    @Test
    void limitAtmYearTest() {
        // TODO: test limitAtmYear
    }

    /**
     * Test the property 'limitAtmMonth'
     */
    @Test
    void limitAtmMonthTest() {
        // TODO: test limitAtmMonth
    }

    /**
     * Test the property 'limitAtmWeek'
     */
    @Test
    void limitAtmWeekTest() {
        // TODO: test limitAtmWeek
    }

    /**
     * Test the property 'limitAtmDay'
     */
    @Test
    void limitAtmDayTest() {
        // TODO: test limitAtmDay
    }

    /**
     * Test the property 'limitAtmAll'
     */
    @Test
    void limitAtmAllTest() {
        // TODO: test limitAtmAll
    }

    /**
     * Test the property 'limitPaymentYear'
     */
    @Test
    void limitPaymentYearTest() {
        // TODO: test limitPaymentYear
    }

    /**
     * Test the property 'limitPaymentMonth'
     */
    @Test
    void limitPaymentMonthTest() {
        // TODO: test limitPaymentMonth
    }

    /**
     * Test the property 'limitPaymentWeek'
     */
    @Test
    void limitPaymentWeekTest() {
        // TODO: test limitPaymentWeek
    }

    /**
     * Test the property 'limitPaymentDay'
     */
    @Test
    void limitPaymentDayTest() {
        // TODO: test limitPaymentDay
    }

    /**
     * Test the property 'limitPaymentAll'
     */
    @Test
    void limitPaymentAllTest() {
        // TODO: test limitPaymentAll
    }

    /**
     * Test the property 'paymentDailyLimit'
     */
    @Test
    void paymentDailyLimitTest() {
        // TODO: test paymentDailyLimit
    }

    /**
     * Test the property 'restrictionGroupLimits'
     */
    @Test
    void restrictionGroupLimitsTest() {
        // TODO: test restrictionGroupLimits
    }

}
