/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.ScheduledPaymentFailedPaymentInner;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScheduledPayment2
 */
class ScheduledPayment2Test {
    private final ScheduledPayment2 model = new ScheduledPayment2();

    /**
     * Model tests for ScheduledPayment2
     */
    @Test
    void testScheduledPayment2() {
        // TODO: test ScheduledPayment2
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'scheduledPaymentName'
     */
    @Test
    void scheduledPaymentNameTest() {
        // TODO: test scheduledPaymentName
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'beneficiaryType'
     */
    @Test
    void beneficiaryTypeTest() {
        // TODO: test beneficiaryType
    }

    /**
     * Test the property 'beneficiary'
     */
    @Test
    void beneficiaryTest() {
        // TODO: test beneficiary
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'execAt'
     */
    @Test
    void execAtTest() {
        // TODO: test execAt
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    void endAtTest() {
        // TODO: test endAt
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'period'
     */
    @Test
    void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'beneficiaryLabel'
     */
    @Test
    void beneficiaryLabelTest() {
        // TODO: test beneficiaryLabel
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'amr'
     */
    @Test
    void amrTest() {
        // TODO: test amr
    }

    /**
     * Test the property 'failedPayment'
     */
    @Test
    void failedPaymentTest() {
        // TODO: test failedPayment
    }

    /**
     * Test the property 'endToEndId'
     */
    @Test
    void endToEndIdTest() {
        // TODO: test endToEndId
    }

}
