/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SimulateOperationsRequestOperations
 */
class SimulateOperationsRequestOperationsTest {
    private final SimulateOperationsRequestOperations model = new SimulateOperationsRequestOperations();

    /**
     * Model tests for SimulateOperationsRequestOperations
     */
    @Test
    void testSimulateOperationsRequestOperations() {
        // TODO: test SimulateOperationsRequestOperations
    }

    /**
     * Test the property 'payin'
     */
    @Test
    void payinTest() {
        // TODO: test payin
    }

    /**
     * Test the property 'payinrefund'
     */
    @Test
    void payinrefundTest() {
        // TODO: test payinrefund
    }

    /**
     * Test the property 'payout'
     */
    @Test
    void payoutTest() {
        // TODO: test payout
    }

    /**
     * Test the property 'payoutrefund'
     */
    @Test
    void payoutrefundTest() {
        // TODO: test payoutrefund
    }

    /**
     * Test the property 'transfer'
     */
    @Test
    void transferTest() {
        // TODO: test transfer
    }

    /**
     * Test the property 'transferrefund'
     */
    @Test
    void transferrefundTest() {
        // TODO: test transferrefund
    }

    /**
     * Test the property 'cardtransaction'
     */
    @Test
    void cardtransactionTest() {
        // TODO: test cardtransaction
    }

    /**
     * Test the property 'transferfees'
     */
    @Test
    void transferfeesTest() {
        // TODO: test transferfees
    }

    /**
     * Test the property 'transfercreditnote'
     */
    @Test
    void transfercreditnoteTest() {
        // TODO: test transfercreditnote
    }

}
