/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatementPayout
 */
class StatementPayoutTest {
    private final StatementPayout model = new StatementPayout();

    /**
     * Model tests for StatementPayout
     */
    @Test
    void testStatementPayout() {
        // TODO: test StatementPayout
    }

    /**
     * Test the property 'payoutId'
     */
    @Test
    void payoutIdTest() {
        // TODO: test payoutId
    }

    /**
     * Test the property 'payoutTag'
     */
    @Test
    void payoutTagTest() {
        // TODO: test payoutTag
    }

    /**
     * Test the property 'label'
     */
    @Test
    void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'beneficiaryId'
     */
    @Test
    void beneficiaryIdTest() {
        // TODO: test beneficiaryId
    }

    /**
     * Test the property 'beneficiaryName'
     */
    @Test
    void beneficiaryNameTest() {
        // TODO: test beneficiaryName
    }

    /**
     * Test the property 'endToEndId'
     */
    @Test
    void endToEndIdTest() {
        // TODO: test endToEndId
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'reasonDescription'
     */
    @Test
    void reasonDescriptionTest() {
        // TODO: test reasonDescription
    }

    /**
     * Test the property 'uniqueMandateReference'
     */
    @Test
    void uniqueMandateReferenceTest() {
        // TODO: test uniqueMandateReference
    }

}
