/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CaptureResponse
 */
@JsonPropertyOrder({
  CaptureResponse.JSON_PROPERTY_OPERATION,
  CaptureResponse.JSON_PROPERTY_PROFILE,
  CaptureResponse.JSON_PROPERTY_AUTHORIZATION_CODE,
  CaptureResponse.JSON_PROPERTY_TRANSACTION_REFERENCE,
  CaptureResponse.JSON_PROPERTY_DATE_CREATED,
  CaptureResponse.JSON_PROPERTY_DATE_UPDATED,
  CaptureResponse.JSON_PROPERTY_DATE_AUTHORIZED,
  CaptureResponse.JSON_PROPERTY_STATUS,
  CaptureResponse.JSON_PROPERTY_MESSAGE,
  CaptureResponse.JSON_PROPERTY_AUTHORIZED_AMOUNT,
  CaptureResponse.JSON_PROPERTY_CAPTURED_AMOUNT,
  CaptureResponse.JSON_PROPERTY_REFUNDED_AMOUNT,
  CaptureResponse.JSON_PROPERTY_DECIMALS,
  CaptureResponse.JSON_PROPERTY_CURRENCY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class CaptureResponse {
  public static final String JSON_PROPERTY_OPERATION = "operation";
  @javax.annotation.Nullable
  private String operation;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  @javax.annotation.Nullable
  private String profile;

  public static final String JSON_PROPERTY_AUTHORIZATION_CODE = "authorizationCode";
  @javax.annotation.Nullable
  private String authorizationCode;

  public static final String JSON_PROPERTY_TRANSACTION_REFERENCE = "transactionReference";
  @javax.annotation.Nullable
  private String transactionReference;

  public static final String JSON_PROPERTY_DATE_CREATED = "dateCreated";
  @javax.annotation.Nullable
  private String dateCreated;

  public static final String JSON_PROPERTY_DATE_UPDATED = "dateUpdated";
  @javax.annotation.Nullable
  private String dateUpdated;

  public static final String JSON_PROPERTY_DATE_AUTHORIZED = "dateAuthorized";
  @javax.annotation.Nullable
  private String dateAuthorized;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_AUTHORIZED_AMOUNT = "authorizedAmount";
  @javax.annotation.Nullable
  private String authorizedAmount;

  public static final String JSON_PROPERTY_CAPTURED_AMOUNT = "capturedAmount";
  @javax.annotation.Nullable
  private String capturedAmount;

  public static final String JSON_PROPERTY_REFUNDED_AMOUNT = "refundedAmount";
  @javax.annotation.Nullable
  private String refundedAmount;

  public static final String JSON_PROPERTY_DECIMALS = "decimals";
  @javax.annotation.Nullable
  private String decimals;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public CaptureResponse() {
  }

  public CaptureResponse operation(@javax.annotation.Nullable String operation) {
    
    this.operation = operation;
    return this;
  }

  /**
   * This value will always be &#39;capture&#39;.
   * @return operation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOperation() {
    return operation;
  }


  @JsonProperty(JSON_PROPERTY_OPERATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperation(@javax.annotation.Nullable String operation) {
    this.operation = operation;
  }

  public CaptureResponse profile(@javax.annotation.Nullable String profile) {
    
    this.profile = profile;
    return this;
  }

  /**
   * HiPay merchant identifier (mid), also known as profile
   * @return profile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(@javax.annotation.Nullable String profile) {
    this.profile = profile;
  }

  public CaptureResponse authorizationCode(@javax.annotation.Nullable String authorizationCode) {
    
    this.authorizationCode = authorizationCode;
    return this;
  }

  /**
   * HiPay authorization code linked to the payin
   * @return authorizationCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthorizationCode() {
    return authorizationCode;
  }


  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorizationCode(@javax.annotation.Nullable String authorizationCode) {
    this.authorizationCode = authorizationCode;
  }

  public CaptureResponse transactionReference(@javax.annotation.Nullable String transactionReference) {
    
    this.transactionReference = transactionReference;
    return this;
  }

  /**
   * The reference of the transaction
   * @return transactionReference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionReference() {
    return transactionReference;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionReference(@javax.annotation.Nullable String transactionReference) {
    this.transactionReference = transactionReference;
  }

  public CaptureResponse dateCreated(@javax.annotation.Nullable String dateCreated) {
    
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * The creation date of the payin
   * @return dateCreated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateCreated() {
    return dateCreated;
  }


  @JsonProperty(JSON_PROPERTY_DATE_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateCreated(@javax.annotation.Nullable String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public CaptureResponse dateUpdated(@javax.annotation.Nullable String dateUpdated) {
    
    this.dateUpdated = dateUpdated;
    return this;
  }

  /**
   * The last update date of the payin
   * @return dateUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateUpdated() {
    return dateUpdated;
  }


  @JsonProperty(JSON_PROPERTY_DATE_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateUpdated(@javax.annotation.Nullable String dateUpdated) {
    this.dateUpdated = dateUpdated;
  }

  public CaptureResponse dateAuthorized(@javax.annotation.Nullable String dateAuthorized) {
    
    this.dateAuthorized = dateAuthorized;
    return this;
  }

  /**
   * The authorized date of the payin
   * @return dateAuthorized
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_AUTHORIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateAuthorized() {
    return dateAuthorized;
  }


  @JsonProperty(JSON_PROPERTY_DATE_AUTHORIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateAuthorized(@javax.annotation.Nullable String dateAuthorized) {
    this.dateAuthorized = dateAuthorized;
  }

  public CaptureResponse status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Transaction status returned by HiPay
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public CaptureResponse message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Message returned by HiPay
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public CaptureResponse authorizedAmount(@javax.annotation.Nullable String authorizedAmount) {
    
    this.authorizedAmount = authorizedAmount;
    return this;
  }

  /**
   * Authorized amount
   * @return authorizedAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHORIZED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthorizedAmount() {
    return authorizedAmount;
  }


  @JsonProperty(JSON_PROPERTY_AUTHORIZED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthorizedAmount(@javax.annotation.Nullable String authorizedAmount) {
    this.authorizedAmount = authorizedAmount;
  }

  public CaptureResponse capturedAmount(@javax.annotation.Nullable String capturedAmount) {
    
    this.capturedAmount = capturedAmount;
    return this;
  }

  /**
   * Captured amount
   * @return capturedAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPTURED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCapturedAmount() {
    return capturedAmount;
  }


  @JsonProperty(JSON_PROPERTY_CAPTURED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapturedAmount(@javax.annotation.Nullable String capturedAmount) {
    this.capturedAmount = capturedAmount;
  }

  public CaptureResponse refundedAmount(@javax.annotation.Nullable String refundedAmount) {
    
    this.refundedAmount = refundedAmount;
    return this;
  }

  /**
   * Refunded amount
   * @return refundedAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUNDED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundedAmount() {
    return refundedAmount;
  }


  @JsonProperty(JSON_PROPERTY_REFUNDED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundedAmount(@javax.annotation.Nullable String refundedAmount) {
    this.refundedAmount = refundedAmount;
  }

  public CaptureResponse decimals(@javax.annotation.Nullable String decimals) {
    
    this.decimals = decimals;
    return this;
  }

  /**
   * The number of digits after the decimal point of the transaction amount 
   * @return decimals
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DECIMALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDecimals() {
    return decimals;
  }


  @JsonProperty(JSON_PROPERTY_DECIMALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDecimals(@javax.annotation.Nullable String decimals) {
    this.decimals = decimals;
  }

  public CaptureResponse currency(@javax.annotation.Nullable String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Base currency for this payin  This three-character currency code must comply with ISO-4217
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaptureResponse captureResponse = (CaptureResponse) o;
    return Objects.equals(this.operation, captureResponse.operation) &&
        Objects.equals(this.profile, captureResponse.profile) &&
        Objects.equals(this.authorizationCode, captureResponse.authorizationCode) &&
        Objects.equals(this.transactionReference, captureResponse.transactionReference) &&
        Objects.equals(this.dateCreated, captureResponse.dateCreated) &&
        Objects.equals(this.dateUpdated, captureResponse.dateUpdated) &&
        Objects.equals(this.dateAuthorized, captureResponse.dateAuthorized) &&
        Objects.equals(this.status, captureResponse.status) &&
        Objects.equals(this.message, captureResponse.message) &&
        Objects.equals(this.authorizedAmount, captureResponse.authorizedAmount) &&
        Objects.equals(this.capturedAmount, captureResponse.capturedAmount) &&
        Objects.equals(this.refundedAmount, captureResponse.refundedAmount) &&
        Objects.equals(this.decimals, captureResponse.decimals) &&
        Objects.equals(this.currency, captureResponse.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, profile, authorizationCode, transactionReference, dateCreated, dateUpdated, dateAuthorized, status, message, authorizedAmount, capturedAmount, refundedAmount, decimals, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaptureResponse {\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    authorizationCode: ").append(toIndentedString(authorizationCode)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    dateAuthorized: ").append(toIndentedString(dateAuthorized)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    authorizedAmount: ").append(toIndentedString(authorizedAmount)).append("\n");
    sb.append("    capturedAmount: ").append(toIndentedString(capturedAmount)).append("\n");
    sb.append("    refundedAmount: ").append(toIndentedString(refundedAmount)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

