/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Chargeback
 */
@JsonPropertyOrder({
  Chargeback.JSON_PROPERTY_PAYIN_ID,
  Chargeback.JSON_PROPERTY_PAYIN_REFUND_ID,
  Chargeback.JSON_PROPERTY_TRANSACTION_REFERENCE,
  Chargeback.JSON_PROPERTY_PAYIN_TAG,
  Chargeback.JSON_PROPERTY_ADDITIONAL_DATA,
  Chargeback.JSON_PROPERTY_CHARGEBACK_REASON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class Chargeback {
  public static final String JSON_PROPERTY_PAYIN_ID = "payinId";
  @javax.annotation.Nullable
  private String payinId;

  public static final String JSON_PROPERTY_PAYIN_REFUND_ID = "payinRefundId";
  @javax.annotation.Nullable
  private String payinRefundId;

  public static final String JSON_PROPERTY_TRANSACTION_REFERENCE = "transactionReference";
  @javax.annotation.Nullable
  private String transactionReference;

  public static final String JSON_PROPERTY_PAYIN_TAG = "payinTag";
  @javax.annotation.Nullable
  private JsonNullable<String> payinTag = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ADDITIONAL_DATA = "additionalData";
  @javax.annotation.Nullable
  private List<String> additionalData = new ArrayList<>();

  public static final String JSON_PROPERTY_CHARGEBACK_REASON = "chargebackReason";
  @javax.annotation.Nullable
  private String chargebackReason;

  public Chargeback() {
  }

  public Chargeback payinId(@javax.annotation.Nullable String payinId) {
    
    this.payinId = payinId;
    return this;
  }

  /**
   * Get payinId
   * @return payinId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYIN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayinId() {
    return payinId;
  }


  @JsonProperty(JSON_PROPERTY_PAYIN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinId(@javax.annotation.Nullable String payinId) {
    this.payinId = payinId;
  }

  public Chargeback payinRefundId(@javax.annotation.Nullable String payinRefundId) {
    
    this.payinRefundId = payinRefundId;
    return this;
  }

  /**
   * Get payinRefundId
   * @return payinRefundId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYIN_REFUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayinRefundId() {
    return payinRefundId;
  }


  @JsonProperty(JSON_PROPERTY_PAYIN_REFUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinRefundId(@javax.annotation.Nullable String payinRefundId) {
    this.payinRefundId = payinRefundId;
  }

  public Chargeback transactionReference(@javax.annotation.Nullable String transactionReference) {
    
    this.transactionReference = transactionReference;
    return this;
  }

  /**
   * Get transactionReference
   * @return transactionReference
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionReference() {
    return transactionReference;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionReference(@javax.annotation.Nullable String transactionReference) {
    this.transactionReference = transactionReference;
  }

  public Chargeback payinTag(@javax.annotation.Nullable String payinTag) {
    this.payinTag = JsonNullable.<String>of(payinTag);
    
    return this;
  }

  /**
   * Get payinTag
   * @return payinTag
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPayinTag() {
        return payinTag.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PAYIN_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPayinTag_JsonNullable() {
    return payinTag;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYIN_TAG)
  public void setPayinTag_JsonNullable(JsonNullable<String> payinTag) {
    this.payinTag = payinTag;
  }

  public void setPayinTag(@javax.annotation.Nullable String payinTag) {
    this.payinTag = JsonNullable.<String>of(payinTag);
  }

  public Chargeback additionalData(@javax.annotation.Nullable List<String> additionalData) {
    
    this.additionalData = additionalData;
    return this;
  }

  public Chargeback addAdditionalDataItem(String additionalDataItem) {
    if (this.additionalData == null) {
      this.additionalData = new ArrayList<>();
    }
    this.additionalData.add(additionalDataItem);
    return this;
  }

  /**
   * Get additionalData
   * @return additionalData
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAdditionalData() {
    return additionalData;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalData(@javax.annotation.Nullable List<String> additionalData) {
    this.additionalData = additionalData;
  }

  public Chargeback chargebackReason(@javax.annotation.Nullable String chargebackReason) {
    
    this.chargebackReason = chargebackReason;
    return this;
  }

  /**
   * Get chargebackReason
   * @return chargebackReason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGEBACK_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChargebackReason() {
    return chargebackReason;
  }


  @JsonProperty(JSON_PROPERTY_CHARGEBACK_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargebackReason(@javax.annotation.Nullable String chargebackReason) {
    this.chargebackReason = chargebackReason;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chargeback chargeback = (Chargeback) o;
    return Objects.equals(this.payinId, chargeback.payinId) &&
        Objects.equals(this.payinRefundId, chargeback.payinRefundId) &&
        Objects.equals(this.transactionReference, chargeback.transactionReference) &&
        equalsNullable(this.payinTag, chargeback.payinTag) &&
        Objects.equals(this.additionalData, chargeback.additionalData) &&
        Objects.equals(this.chargebackReason, chargeback.chargebackReason);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(payinId, payinRefundId, transactionReference, hashCodeNullable(payinTag), additionalData, chargebackReason);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chargeback {\n");
    sb.append("    payinId: ").append(toIndentedString(payinId)).append("\n");
    sb.append("    payinRefundId: ").append(toIndentedString(payinRefundId)).append("\n");
    sb.append("    transactionReference: ").append(toIndentedString(transactionReference)).append("\n");
    sb.append("    payinTag: ").append(toIndentedString(payinTag)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    chargebackReason: ").append(toIndentedString(chargebackReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

