/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateRuleset201Response
 */
@JsonPropertyOrder({
  CreateRuleset201Response.JSON_PROPERTY_RULESET_ID
})
@JsonTypeName("create_ruleset_201_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class CreateRuleset201Response {
  public static final String JSON_PROPERTY_RULESET_ID = "rulesetId";
  @javax.annotation.Nullable
  private String rulesetId;

  public CreateRuleset201Response() {
  }

  public CreateRuleset201Response rulesetId(@javax.annotation.Nullable String rulesetId) {
    
    this.rulesetId = rulesetId;
    return this;
  }

  /**
   * Get rulesetId
   * @return rulesetId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RULESET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRulesetId() {
    return rulesetId;
  }


  @JsonProperty(JSON_PROPERTY_RULESET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRulesetId(@javax.annotation.Nullable String rulesetId) {
    this.rulesetId = rulesetId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRuleset201Response createRuleset201Response = (CreateRuleset201Response) o;
    return Objects.equals(this.rulesetId, createRuleset201Response.rulesetId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rulesetId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRuleset201Response {\n");
    sb.append("    rulesetId: ").append(toIndentedString(rulesetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

