/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.DeletePayout200ResponsePayoutsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeletePayout200Response
 */
@JsonPropertyOrder({
  DeletePayout200Response.JSON_PROPERTY_PAYOUTS
})
@JsonTypeName("deletePayout_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class DeletePayout200Response {
  public static final String JSON_PROPERTY_PAYOUTS = "payouts";
  @javax.annotation.Nullable
  private List<DeletePayout200ResponsePayoutsInner> payouts = new ArrayList<>();

  public DeletePayout200Response() {
  }

  public DeletePayout200Response payouts(@javax.annotation.Nullable List<DeletePayout200ResponsePayoutsInner> payouts) {
    
    this.payouts = payouts;
    return this;
  }

  public DeletePayout200Response addPayoutsItem(DeletePayout200ResponsePayoutsInner payoutsItem) {
    if (this.payouts == null) {
      this.payouts = new ArrayList<>();
    }
    this.payouts.add(payoutsItem);
    return this;
  }

  /**
   * Get payouts
   * @return payouts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DeletePayout200ResponsePayoutsInner> getPayouts() {
    return payouts;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayouts(@javax.annotation.Nullable List<DeletePayout200ResponsePayoutsInner> payouts) {
    this.payouts = payouts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeletePayout200Response deletePayout200Response = (DeletePayout200Response) o;
    return Objects.equals(this.payouts, deletePayout200Response.payouts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payouts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeletePayout200Response {\n");
    sb.append("    payouts: ").append(toIndentedString(payouts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

