/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.GetFactsBalance200ResponseFactsMonthTotalAmount;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetFactsBalance200ResponseFacts
 */
@JsonPropertyOrder({
  GetFactsBalance200ResponseFacts.JSON_PROPERTY_MONTH_TOTAL_AMOUNT
})
@JsonTypeName("getFactsBalance_200_response_facts")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class GetFactsBalance200ResponseFacts {
  public static final String JSON_PROPERTY_MONTH_TOTAL_AMOUNT = "month_total_amount";
  @javax.annotation.Nullable
  private GetFactsBalance200ResponseFactsMonthTotalAmount monthTotalAmount;

  public GetFactsBalance200ResponseFacts() {
  }

  public GetFactsBalance200ResponseFacts monthTotalAmount(@javax.annotation.Nullable GetFactsBalance200ResponseFactsMonthTotalAmount monthTotalAmount) {
    
    this.monthTotalAmount = monthTotalAmount;
    return this;
  }

  /**
   * Get monthTotalAmount
   * @return monthTotalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONTH_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetFactsBalance200ResponseFactsMonthTotalAmount getMonthTotalAmount() {
    return monthTotalAmount;
  }


  @JsonProperty(JSON_PROPERTY_MONTH_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonthTotalAmount(@javax.annotation.Nullable GetFactsBalance200ResponseFactsMonthTotalAmount monthTotalAmount) {
    this.monthTotalAmount = monthTotalAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFactsBalance200ResponseFacts getFactsBalance200ResponseFacts = (GetFactsBalance200ResponseFacts) o;
    return Objects.equals(this.monthTotalAmount, getFactsBalance200ResponseFacts.monthTotalAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monthTotalAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFactsBalance200ResponseFacts {\n");
    sb.append("    monthTotalAmount: ").append(toIndentedString(monthTotalAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

