/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.GetPreSignedKycForm200ResponseForm;
import com.sdk.treezor.model.GetPreSignedKycForm200ResponseFormFields;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetPreSignedKycForm200Response
 */
@JsonPropertyOrder({
  GetPreSignedKycForm200Response.JSON_PROPERTY_DOCUMENT_ID,
  GetPreSignedKycForm200Response.JSON_PROPERTY_FORM,
  GetPreSignedKycForm200Response.JSON_PROPERTY_FORM_FIELDS,
  GetPreSignedKycForm200Response.JSON_PROPERTY_EXPIRE_IN
})
@JsonTypeName("getPreSignedKycForm_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class GetPreSignedKycForm200Response {
  public static final String JSON_PROPERTY_DOCUMENT_ID = "documentId";
  @javax.annotation.Nullable
  private UUID documentId;

  public static final String JSON_PROPERTY_FORM = "form";
  @javax.annotation.Nullable
  private GetPreSignedKycForm200ResponseForm form;

  public static final String JSON_PROPERTY_FORM_FIELDS = "formFields";
  @javax.annotation.Nullable
  private GetPreSignedKycForm200ResponseFormFields formFields;

  public static final String JSON_PROPERTY_EXPIRE_IN = "expireIn";
  @javax.annotation.Nullable
  private Integer expireIn;

  public GetPreSignedKycForm200Response() {
  }

  public GetPreSignedKycForm200Response documentId(@javax.annotation.Nullable UUID documentId) {
    
    this.documentId = documentId;
    return this;
  }

  /**
   * The unique identifier of the pre-review document. This is different from the Id of the Document object. 
   * @return documentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDocumentId() {
    return documentId;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentId(@javax.annotation.Nullable UUID documentId) {
    this.documentId = documentId;
  }

  public GetPreSignedKycForm200Response form(@javax.annotation.Nullable GetPreSignedKycForm200ResponseForm form) {
    
    this.form = form;
    return this;
  }

  /**
   * Get form
   * @return form
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetPreSignedKycForm200ResponseForm getForm() {
    return form;
  }


  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForm(@javax.annotation.Nullable GetPreSignedKycForm200ResponseForm form) {
    this.form = form;
  }

  public GetPreSignedKycForm200Response formFields(@javax.annotation.Nullable GetPreSignedKycForm200ResponseFormFields formFields) {
    
    this.formFields = formFields;
    return this;
  }

  /**
   * Get formFields
   * @return formFields
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetPreSignedKycForm200ResponseFormFields getFormFields() {
    return formFields;
  }


  @JsonProperty(JSON_PROPERTY_FORM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormFields(@javax.annotation.Nullable GetPreSignedKycForm200ResponseFormFields formFields) {
    this.formFields = formFields;
  }

  public GetPreSignedKycForm200Response expireIn(@javax.annotation.Nullable Integer expireIn) {
    
    this.expireIn = expireIn;
    return this;
  }

  /**
   * The time after which the form expires in seconds.
   * @return expireIn
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRE_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExpireIn() {
    return expireIn;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpireIn(@javax.annotation.Nullable Integer expireIn) {
    this.expireIn = expireIn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPreSignedKycForm200Response getPreSignedKycForm200Response = (GetPreSignedKycForm200Response) o;
    return Objects.equals(this.documentId, getPreSignedKycForm200Response.documentId) &&
        Objects.equals(this.form, getPreSignedKycForm200Response.form) &&
        Objects.equals(this.formFields, getPreSignedKycForm200Response.formFields) &&
        Objects.equals(this.expireIn, getPreSignedKycForm200Response.expireIn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, form, formFields, expireIn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPreSignedKycForm200Response {\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    formFields: ").append(toIndentedString(formFields)).append("\n");
    sb.append("    expireIn: ").append(toIndentedString(expireIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

