/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetPreSignedKycForm200ResponseFormFields
 */
@JsonPropertyOrder({
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_ACL,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_KEY,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_CONTENT_TYPE,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_X_AMZ_SECURITY_TOKEN,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_X_AMZ_CREDENTIAL,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_X_AMZ_ALGORITHM,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_X_AMZ_DATE,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_POLICY,
  GetPreSignedKycForm200ResponseFormFields.JSON_PROPERTY_X_AMZ_SIGNATURE
})
@JsonTypeName("getPreSignedKycForm_200_response_formFields")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class GetPreSignedKycForm200ResponseFormFields {
  public static final String JSON_PROPERTY_ACL = "acl";
  @javax.annotation.Nullable
  private String acl;

  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "Content-Type";
  @javax.annotation.Nullable
  private String contentType;

  public static final String JSON_PROPERTY_X_AMZ_SECURITY_TOKEN = "X-Amz-Security-Token";
  @javax.annotation.Nullable
  private String xAmzSecurityToken;

  public static final String JSON_PROPERTY_X_AMZ_CREDENTIAL = "X-Amz-Credential";
  @javax.annotation.Nullable
  private String xAmzCredential;

  public static final String JSON_PROPERTY_X_AMZ_ALGORITHM = "X-Amz-Algorithm";
  @javax.annotation.Nullable
  private String xAmzAlgorithm;

  public static final String JSON_PROPERTY_X_AMZ_DATE = "X-Amz-Date";
  @javax.annotation.Nullable
  private String xAmzDate;

  public static final String JSON_PROPERTY_POLICY = "Policy";
  @javax.annotation.Nullable
  private String policy;

  public static final String JSON_PROPERTY_X_AMZ_SIGNATURE = "X-Amz-Signature";
  @javax.annotation.Nullable
  private String xAmzSignature;

  public GetPreSignedKycForm200ResponseFormFields() {
  }

  public GetPreSignedKycForm200ResponseFormFields acl(@javax.annotation.Nullable String acl) {
    
    this.acl = acl;
    return this;
  }

  /**
   * Get acl
   * @return acl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcl() {
    return acl;
  }


  @JsonProperty(JSON_PROPERTY_ACL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcl(@javax.annotation.Nullable String acl) {
    this.acl = acl;
  }

  public GetPreSignedKycForm200ResponseFormFields key(@javax.annotation.Nullable String key) {
    
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }

  public GetPreSignedKycForm200ResponseFormFields contentType(@javax.annotation.Nullable String contentType) {
    
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContentType() {
    return contentType;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentType(@javax.annotation.Nullable String contentType) {
    this.contentType = contentType;
  }

  public GetPreSignedKycForm200ResponseFormFields xAmzSecurityToken(@javax.annotation.Nullable String xAmzSecurityToken) {
    
    this.xAmzSecurityToken = xAmzSecurityToken;
    return this;
  }

  /**
   * Get xAmzSecurityToken
   * @return xAmzSecurityToken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AMZ_SECURITY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxAmzSecurityToken() {
    return xAmzSecurityToken;
  }


  @JsonProperty(JSON_PROPERTY_X_AMZ_SECURITY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAmzSecurityToken(@javax.annotation.Nullable String xAmzSecurityToken) {
    this.xAmzSecurityToken = xAmzSecurityToken;
  }

  public GetPreSignedKycForm200ResponseFormFields xAmzCredential(@javax.annotation.Nullable String xAmzCredential) {
    
    this.xAmzCredential = xAmzCredential;
    return this;
  }

  /**
   * Get xAmzCredential
   * @return xAmzCredential
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AMZ_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxAmzCredential() {
    return xAmzCredential;
  }


  @JsonProperty(JSON_PROPERTY_X_AMZ_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAmzCredential(@javax.annotation.Nullable String xAmzCredential) {
    this.xAmzCredential = xAmzCredential;
  }

  public GetPreSignedKycForm200ResponseFormFields xAmzAlgorithm(@javax.annotation.Nullable String xAmzAlgorithm) {
    
    this.xAmzAlgorithm = xAmzAlgorithm;
    return this;
  }

  /**
   * Get xAmzAlgorithm
   * @return xAmzAlgorithm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AMZ_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxAmzAlgorithm() {
    return xAmzAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_X_AMZ_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAmzAlgorithm(@javax.annotation.Nullable String xAmzAlgorithm) {
    this.xAmzAlgorithm = xAmzAlgorithm;
  }

  public GetPreSignedKycForm200ResponseFormFields xAmzDate(@javax.annotation.Nullable String xAmzDate) {
    
    this.xAmzDate = xAmzDate;
    return this;
  }

  /**
   * Get xAmzDate
   * @return xAmzDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AMZ_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxAmzDate() {
    return xAmzDate;
  }


  @JsonProperty(JSON_PROPERTY_X_AMZ_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAmzDate(@javax.annotation.Nullable String xAmzDate) {
    this.xAmzDate = xAmzDate;
  }

  public GetPreSignedKycForm200ResponseFormFields policy(@javax.annotation.Nullable String policy) {
    
    this.policy = policy;
    return this;
  }

  /**
   * Get policy
   * @return policy
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPolicy() {
    return policy;
  }


  @JsonProperty(JSON_PROPERTY_POLICY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPolicy(@javax.annotation.Nullable String policy) {
    this.policy = policy;
  }

  public GetPreSignedKycForm200ResponseFormFields xAmzSignature(@javax.annotation.Nullable String xAmzSignature) {
    
    this.xAmzSignature = xAmzSignature;
    return this;
  }

  /**
   * Get xAmzSignature
   * @return xAmzSignature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X_AMZ_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getxAmzSignature() {
    return xAmzSignature;
  }


  @JsonProperty(JSON_PROPERTY_X_AMZ_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setxAmzSignature(@javax.annotation.Nullable String xAmzSignature) {
    this.xAmzSignature = xAmzSignature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPreSignedKycForm200ResponseFormFields getPreSignedKycForm200ResponseFormFields = (GetPreSignedKycForm200ResponseFormFields) o;
    return Objects.equals(this.acl, getPreSignedKycForm200ResponseFormFields.acl) &&
        Objects.equals(this.key, getPreSignedKycForm200ResponseFormFields.key) &&
        Objects.equals(this.contentType, getPreSignedKycForm200ResponseFormFields.contentType) &&
        Objects.equals(this.xAmzSecurityToken, getPreSignedKycForm200ResponseFormFields.xAmzSecurityToken) &&
        Objects.equals(this.xAmzCredential, getPreSignedKycForm200ResponseFormFields.xAmzCredential) &&
        Objects.equals(this.xAmzAlgorithm, getPreSignedKycForm200ResponseFormFields.xAmzAlgorithm) &&
        Objects.equals(this.xAmzDate, getPreSignedKycForm200ResponseFormFields.xAmzDate) &&
        Objects.equals(this.policy, getPreSignedKycForm200ResponseFormFields.policy) &&
        Objects.equals(this.xAmzSignature, getPreSignedKycForm200ResponseFormFields.xAmzSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acl, key, contentType, xAmzSecurityToken, xAmzCredential, xAmzAlgorithm, xAmzDate, policy, xAmzSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPreSignedKycForm200ResponseFormFields {\n");
    sb.append("    acl: ").append(toIndentedString(acl)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    xAmzSecurityToken: ").append(toIndentedString(xAmzSecurityToken)).append("\n");
    sb.append("    xAmzCredential: ").append(toIndentedString(xAmzCredential)).append("\n");
    sb.append("    xAmzAlgorithm: ").append(toIndentedString(xAmzAlgorithm)).append("\n");
    sb.append("    xAmzDate: ").append(toIndentedString(xAmzDate)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    xAmzSignature: ").append(toIndentedString(xAmzSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

