/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetRawStatement200ResponseUser
 */
@JsonPropertyOrder({
  GetRawStatement200ResponseUser.JSON_PROPERTY_TITLE,
  GetRawStatement200ResponseUser.JSON_PROPERTY_FIRSTNAME,
  GetRawStatement200ResponseUser.JSON_PROPERTY_LASTNAME,
  GetRawStatement200ResponseUser.JSON_PROPERTY_ADDRESS1,
  GetRawStatement200ResponseUser.JSON_PROPERTY_ADDRESS2,
  GetRawStatement200ResponseUser.JSON_PROPERTY_ADDRESS3,
  GetRawStatement200ResponseUser.JSON_PROPERTY_POSTCODE,
  GetRawStatement200ResponseUser.JSON_PROPERTY_CITY,
  GetRawStatement200ResponseUser.JSON_PROPERTY_COUNTRY,
  GetRawStatement200ResponseUser.JSON_PROPERTY_USER_TYPE_ID,
  GetRawStatement200ResponseUser.JSON_PROPERTY_STATE,
  GetRawStatement200ResponseUser.JSON_PROPERTY_LEGAL_NAME,
  GetRawStatement200ResponseUser.JSON_PROPERTY_LEGAL_REGISTRATION_NUMBER
})
@JsonTypeName("getRawStatement_200_response_user")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class GetRawStatement200ResponseUser {
  /**
   * Gets or Sets title
   */
  public enum TitleEnum {
    M(String.valueOf("M")),
    
    MLLE(String.valueOf("MLLE")),
    
    MME(String.valueOf("MME"));

    private String value;

    TitleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TitleEnum fromValue(String value) {
      for (TitleEnum b : TitleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private TitleEnum title;

  public static final String JSON_PROPERTY_FIRSTNAME = "firstname";
  @javax.annotation.Nullable
  private String firstname;

  public static final String JSON_PROPERTY_LASTNAME = "lastname";
  @javax.annotation.Nullable
  private String lastname;

  public static final String JSON_PROPERTY_ADDRESS1 = "address1";
  @javax.annotation.Nullable
  private String address1;

  public static final String JSON_PROPERTY_ADDRESS2 = "address2";
  @javax.annotation.Nullable
  private String address2;

  public static final String JSON_PROPERTY_ADDRESS3 = "address3";
  @javax.annotation.Nullable
  private String address3;

  public static final String JSON_PROPERTY_POSTCODE = "postcode";
  @javax.annotation.Nullable
  private String postcode;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_USER_TYPE_ID = "userTypeId";
  @javax.annotation.Nullable
  private Integer userTypeId;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_LEGAL_NAME = "legalName";
  @javax.annotation.Nullable
  private String legalName;

  public static final String JSON_PROPERTY_LEGAL_REGISTRATION_NUMBER = "legalRegistrationNumber";
  @javax.annotation.Nullable
  private String legalRegistrationNumber;

  public GetRawStatement200ResponseUser() {
  }

  public GetRawStatement200ResponseUser title(@javax.annotation.Nullable TitleEnum title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TitleEnum getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable TitleEnum title) {
    this.title = title;
  }

  public GetRawStatement200ResponseUser firstname(@javax.annotation.Nullable String firstname) {
    
    this.firstname = firstname;
    return this;
  }

  /**
   * Get firstname
   * @return firstname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstname() {
    return firstname;
  }


  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstname(@javax.annotation.Nullable String firstname) {
    this.firstname = firstname;
  }

  public GetRawStatement200ResponseUser lastname(@javax.annotation.Nullable String lastname) {
    
    this.lastname = lastname;
    return this;
  }

  /**
   * Get lastname
   * @return lastname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LASTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastname() {
    return lastname;
  }


  @JsonProperty(JSON_PROPERTY_LASTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastname(@javax.annotation.Nullable String lastname) {
    this.lastname = lastname;
  }

  public GetRawStatement200ResponseUser address1(@javax.annotation.Nullable String address1) {
    
    this.address1 = address1;
    return this;
  }

  /**
   * Get address1
   * @return address1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress1() {
    return address1;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress1(@javax.annotation.Nullable String address1) {
    this.address1 = address1;
  }

  public GetRawStatement200ResponseUser address2(@javax.annotation.Nullable String address2) {
    
    this.address2 = address2;
    return this;
  }

  /**
   * Get address2
   * @return address2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress2() {
    return address2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress2(@javax.annotation.Nullable String address2) {
    this.address2 = address2;
  }

  public GetRawStatement200ResponseUser address3(@javax.annotation.Nullable String address3) {
    
    this.address3 = address3;
    return this;
  }

  /**
   * Get address3
   * @return address3
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress3() {
    return address3;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress3(@javax.annotation.Nullable String address3) {
    this.address3 = address3;
  }

  public GetRawStatement200ResponseUser postcode(@javax.annotation.Nullable String postcode) {
    
    this.postcode = postcode;
    return this;
  }

  /**
   * Get postcode
   * @return postcode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostcode() {
    return postcode;
  }


  @JsonProperty(JSON_PROPERTY_POSTCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostcode(@javax.annotation.Nullable String postcode) {
    this.postcode = postcode;
  }

  public GetRawStatement200ResponseUser city(@javax.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }

  public GetRawStatement200ResponseUser country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public GetRawStatement200ResponseUser userTypeId(@javax.annotation.Nullable Integer userTypeId) {
    
    this.userTypeId = userTypeId;
    return this;
  }

  /**
   * Get userTypeId
   * @return userTypeId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserTypeId() {
    return userTypeId;
  }


  @JsonProperty(JSON_PROPERTY_USER_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserTypeId(@javax.annotation.Nullable Integer userTypeId) {
    this.userTypeId = userTypeId;
  }

  public GetRawStatement200ResponseUser state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public GetRawStatement200ResponseUser legalName(@javax.annotation.Nullable String legalName) {
    
    this.legalName = legalName;
    return this;
  }

  /**
   * Get legalName
   * @return legalName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLegalName() {
    return legalName;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalName(@javax.annotation.Nullable String legalName) {
    this.legalName = legalName;
  }

  public GetRawStatement200ResponseUser legalRegistrationNumber(@javax.annotation.Nullable String legalRegistrationNumber) {
    
    this.legalRegistrationNumber = legalRegistrationNumber;
    return this;
  }

  /**
   * Get legalRegistrationNumber
   * @return legalRegistrationNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_REGISTRATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLegalRegistrationNumber() {
    return legalRegistrationNumber;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_REGISTRATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalRegistrationNumber(@javax.annotation.Nullable String legalRegistrationNumber) {
    this.legalRegistrationNumber = legalRegistrationNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRawStatement200ResponseUser getRawStatement200ResponseUser = (GetRawStatement200ResponseUser) o;
    return Objects.equals(this.title, getRawStatement200ResponseUser.title) &&
        Objects.equals(this.firstname, getRawStatement200ResponseUser.firstname) &&
        Objects.equals(this.lastname, getRawStatement200ResponseUser.lastname) &&
        Objects.equals(this.address1, getRawStatement200ResponseUser.address1) &&
        Objects.equals(this.address2, getRawStatement200ResponseUser.address2) &&
        Objects.equals(this.address3, getRawStatement200ResponseUser.address3) &&
        Objects.equals(this.postcode, getRawStatement200ResponseUser.postcode) &&
        Objects.equals(this.city, getRawStatement200ResponseUser.city) &&
        Objects.equals(this.country, getRawStatement200ResponseUser.country) &&
        Objects.equals(this.userTypeId, getRawStatement200ResponseUser.userTypeId) &&
        Objects.equals(this.state, getRawStatement200ResponseUser.state) &&
        Objects.equals(this.legalName, getRawStatement200ResponseUser.legalName) &&
        Objects.equals(this.legalRegistrationNumber, getRawStatement200ResponseUser.legalRegistrationNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, firstname, lastname, address1, address2, address3, postcode, city, country, userTypeId, state, legalName, legalRegistrationNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRawStatement200ResponseUser {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    userTypeId: ").append(toIndentedString(userTypeId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    legalRegistrationNumber: ").append(toIndentedString(legalRegistrationNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

