/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdk.treezor.model.GetCoCardTransactions200ResponseCursor;
import com.sdk.treezor.model.GetScheduledPaymentOperations200ResponsePaymentsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetScheduledPaymentOperations200Response
 */
@JsonPropertyOrder({
  GetScheduledPaymentOperations200Response.JSON_PROPERTY_CURSOR,
  GetScheduledPaymentOperations200Response.JSON_PROPERTY_PAYMENTS
})
@JsonTypeName("getScheduledPaymentOperations_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class GetScheduledPaymentOperations200Response {
  public static final String JSON_PROPERTY_CURSOR = "cursor";
  @javax.annotation.Nullable
  private GetCoCardTransactions200ResponseCursor cursor;

  public static final String JSON_PROPERTY_PAYMENTS = "payments";
  @javax.annotation.Nullable
  private List<GetScheduledPaymentOperations200ResponsePaymentsInner> payments = new ArrayList<>();

  public GetScheduledPaymentOperations200Response() {
  }

  public GetScheduledPaymentOperations200Response cursor(@javax.annotation.Nullable GetCoCardTransactions200ResponseCursor cursor) {
    
    this.cursor = cursor;
    return this;
  }

  /**
   * Get cursor
   * @return cursor
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetCoCardTransactions200ResponseCursor getCursor() {
    return cursor;
  }


  @JsonProperty(JSON_PROPERTY_CURSOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCursor(@javax.annotation.Nullable GetCoCardTransactions200ResponseCursor cursor) {
    this.cursor = cursor;
  }

  public GetScheduledPaymentOperations200Response payments(@javax.annotation.Nullable List<GetScheduledPaymentOperations200ResponsePaymentsInner> payments) {
    
    this.payments = payments;
    return this;
  }

  public GetScheduledPaymentOperations200Response addPaymentsItem(GetScheduledPaymentOperations200ResponsePaymentsInner paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

  /**
   * Get payments
   * @return payments
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetScheduledPaymentOperations200ResponsePaymentsInner> getPayments() {
    return payments;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayments(@javax.annotation.Nullable List<GetScheduledPaymentOperations200ResponsePaymentsInner> payments) {
    this.payments = payments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetScheduledPaymentOperations200Response getScheduledPaymentOperations200Response = (GetScheduledPaymentOperations200Response) o;
    return Objects.equals(this.cursor, getScheduledPaymentOperations200Response.cursor) &&
        Objects.equals(this.payments, getScheduledPaymentOperations200Response.payments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cursor, payments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetScheduledPaymentOperations200Response {\n");
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

