/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ImportMdcMccListCodesRequest
 */
@JsonPropertyOrder({
  ImportMdcMccListCodesRequest.JSON_PROPERTY_CODES
})
@JsonTypeName("importMdcMccListCodes_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class ImportMdcMccListCodesRequest {
  public static final String JSON_PROPERTY_CODES = "codes";
  @javax.annotation.Nullable
  private List<String> codes = new ArrayList<>();

  public ImportMdcMccListCodesRequest() {
  }

  public ImportMdcMccListCodesRequest codes(@javax.annotation.Nullable List<String> codes) {
    
    this.codes = codes;
    return this;
  }

  public ImportMdcMccListCodesRequest addCodesItem(String codesItem) {
    if (this.codes == null) {
      this.codes = new ArrayList<>();
    }
    this.codes.add(codesItem);
    return this;
  }

  /**
   * List of MIDs to import.
   * @return codes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCodes() {
    return codes;
  }


  @JsonProperty(JSON_PROPERTY_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodes(@javax.annotation.Nullable List<String> codes) {
    this.codes = codes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportMdcMccListCodesRequest importMdcMccListCodesRequest = (ImportMdcMccListCodesRequest) o;
    return Objects.equals(this.codes, importMdcMccListCodesRequest.codes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportMdcMccListCodesRequest {\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

