/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ImportMdcMidListCodesRequest
 */
@JsonPropertyOrder({
  ImportMdcMidListCodesRequest.JSON_PROPERTY_MERCHANT_IDS
})
@JsonTypeName("importMdcMidListCodes_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class ImportMdcMidListCodesRequest {
  public static final String JSON_PROPERTY_MERCHANT_IDS = "merchantIds";
  @javax.annotation.Nullable
  private List<String> merchantIds = new ArrayList<>();

  public ImportMdcMidListCodesRequest() {
  }

  public ImportMdcMidListCodesRequest merchantIds(@javax.annotation.Nullable List<String> merchantIds) {
    
    this.merchantIds = merchantIds;
    return this;
  }

  public ImportMdcMidListCodesRequest addMerchantIdsItem(String merchantIdsItem) {
    if (this.merchantIds == null) {
      this.merchantIds = new ArrayList<>();
    }
    this.merchantIds.add(merchantIdsItem);
    return this;
  }

  /**
   * List of MIDs to import.
   * @return merchantIds
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getMerchantIds() {
    return merchantIds;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantIds(@javax.annotation.Nullable List<String> merchantIds) {
    this.merchantIds = merchantIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportMdcMidListCodesRequest importMdcMidListCodesRequest = (ImportMdcMidListCodesRequest) o;
    return Objects.equals(this.merchantIds, importMdcMidListCodesRequest.merchantIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportMdcMidListCodesRequest {\n");
    sb.append("    merchantIds: ").append(toIndentedString(merchantIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

