/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostKycqes201Response
 */
@JsonPropertyOrder({
  PostKycqes201Response.JSON_PROPERTY_IDENTIFICATION_ID,
  PostKycqes201Response.JSON_PROPERTY_IDENTIFICATION_U_R_L
})
@JsonTypeName("postKycqes_201_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class PostKycqes201Response {
  public static final String JSON_PROPERTY_IDENTIFICATION_ID = "identificationId";
  @javax.annotation.Nullable
  private String identificationId;

  public static final String JSON_PROPERTY_IDENTIFICATION_U_R_L = "identificationURL";
  @javax.annotation.Nullable
  private String identificationURL;

  public PostKycqes201Response() {
  }

  public PostKycqes201Response identificationId(@javax.annotation.Nullable String identificationId) {
    
    this.identificationId = identificationId;
    return this;
  }

  /**
   * The identifier of the provider&#39;s verification session.
   * @return identificationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificationId() {
    return identificationId;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationId(@javax.annotation.Nullable String identificationId) {
    this.identificationId = identificationId;
  }

  public PostKycqes201Response identificationURL(@javax.annotation.Nullable String identificationURL) {
    
    this.identificationURL = identificationURL;
    return this;
  }

  /**
   * URL to redirect the end user to so that go through the verification process.
   * @return identificationURL
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificationURL() {
    return identificationURL;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_U_R_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationURL(@javax.annotation.Nullable String identificationURL) {
    this.identificationURL = identificationURL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostKycqes201Response postKycqes201Response = (PostKycqes201Response) o;
    return Objects.equals(this.identificationId, postKycqes201Response.identificationId) &&
        Objects.equals(this.identificationURL, postKycqes201Response.identificationURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationId, identificationURL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostKycqes201Response {\n");
    sb.append("    identificationId: ").append(toIndentedString(identificationId)).append("\n");
    sb.append("    identificationURL: ").append(toIndentedString(identificationURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

