/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostExtOperationRequest
 */
@JsonPropertyOrder({
  PostExtOperationRequest.JSON_PROPERTY_ACTION_NAME,
  PostExtOperationRequest.JSON_PROPERTY_SCA_PROOF,
  PostExtOperationRequest.JSON_PROPERTY_ACTION_DATE,
  PostExtOperationRequest.JSON_PROPERTY_RESOURCE_IDS
})
@JsonTypeName("postExtOperation_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class PostExtOperationRequest {
  /**
   * The end user action that was secured by an SCA. See [list of actions](/guide/strong-customer-authentication/securing-endpoints.html#action-names-actionname) for more information. 
   */
  public enum ActionNameEnum {
    EXTERNAL_DISPLAY_ACCOUNT_DETAILS(String.valueOf("externalDisplayAccountDetails")),
    
    EXTERNAL_GET_BALANCE(String.valueOf("externalGetBalance")),
    
    EXTERNAL_GET_STATEMENT(String.valueOf("externalGetStatement")),
    
    EXTERNAL_MASS_PAYOUT_ORDER_CREATION(String.valueOf("externalMassPayoutOrderCreation")),
    
    EXTERNAL_MASS_TRANSFER_ORDER_CREATION(String.valueOf("externalMassTransferOrderCreation")),
    
    EXTERNAL_OPERATION_VIEW(String.valueOf("externalOperationView")),
    
    EXTERNAL_OPERATION_VIEW90_DAYS(String.valueOf("externalOperationView90Days")),
    
    EXTERNAL_SCHEDULED_PAYOUT_ORDER(String.valueOf("externalScheduledPayoutOrder")),
    
    EXTERNAL_SCHEDULED_TRANSFER_ORDER(String.valueOf("externalScheduledTransferOrder")),
    
    EXTERNAL_UPDATE_LIMITS_CARD(String.valueOf("externalUpdateLimitsCard")),
    
    INTERNAL_CHECK(String.valueOf("internalCheck"));

    private String value;

    ActionNameEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionNameEnum fromValue(String value) {
      for (ActionNameEnum b : ActionNameEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION_NAME = "actionName";
  @javax.annotation.Nullable
  private ActionNameEnum actionName;

  public static final String JSON_PROPERTY_SCA_PROOF = "scaProof";
  @javax.annotation.Nullable
  private JsonNullable<String> scaProof = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ACTION_DATE = "actionDate";
  @javax.annotation.Nullable
  private OffsetDateTime actionDate;

  public static final String JSON_PROPERTY_RESOURCE_IDS = "resourceIds";
  @javax.annotation.Nullable
  private JsonNullable<List<String>> resourceIds = JsonNullable.<List<String>>undefined();

  public PostExtOperationRequest() {
  }

  public PostExtOperationRequest actionName(@javax.annotation.Nullable ActionNameEnum actionName) {
    
    this.actionName = actionName;
    return this;
  }

  /**
   * The end user action that was secured by an SCA. See [list of actions](/guide/strong-customer-authentication/securing-endpoints.html#action-names-actionname) for more information. 
   * @return actionName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionNameEnum getActionName() {
    return actionName;
  }


  @JsonProperty(JSON_PROPERTY_ACTION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionName(@javax.annotation.Nullable ActionNameEnum actionName) {
    this.actionName = actionName;
  }

  public PostExtOperationRequest scaProof(@javax.annotation.Nullable String scaProof) {
    this.scaProof = JsonNullable.<String>of(scaProof);
    
    return this;
  }

  /**
   * The valid proof that authenticated the end user&#39;s action. Required if &#x60;actionName&#x60; is covered by a per-operation SCA. 
   * @return scaProof
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getScaProof() {
        return scaProof.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCA_PROOF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getScaProof_JsonNullable() {
    return scaProof;
  }
  
  @JsonProperty(JSON_PROPERTY_SCA_PROOF)
  public void setScaProof_JsonNullable(JsonNullable<String> scaProof) {
    this.scaProof = scaProof;
  }

  public void setScaProof(@javax.annotation.Nullable String scaProof) {
    this.scaProof = JsonNullable.<String>of(scaProof);
  }

  public PostExtOperationRequest actionDate(@javax.annotation.Nullable OffsetDateTime actionDate) {
    
    this.actionDate = actionDate;
    return this;
  }

  /**
   * The date on which the declared action took place. (Format: RFC3339). 
   * @return actionDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getActionDate() {
    return actionDate;
  }


  @JsonProperty(JSON_PROPERTY_ACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionDate(@javax.annotation.Nullable OffsetDateTime actionDate) {
    this.actionDate = actionDate;
  }

  public PostExtOperationRequest resourceIds(@javax.annotation.Nullable List<String> resourceIds) {
    this.resourceIds = JsonNullable.<List<String>>of(resourceIds);
    
    return this;
  }

  public PostExtOperationRequest addResourceIdsItem(String resourceIdsItem) {
    if (this.resourceIds == null || !this.resourceIds.isPresent()) {
      this.resourceIds = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.resourceIds.get().add(resourceIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * The list of unique identifiers (strings) of the objects, conditionned by the type of action. Must be:  * **walletId** for &#x60;externalGetStatement&#x60;, &#x60;externalGetBalance&#x60;, &#x60;externalOperationView&#x60;, &#x60;externalOperationView90Days&#x60;, and &#x60;externalDisplayAccountDetails&#x60; * **payoutId** for **transferId** in case of a payout or transfer * **cardId** for &#x60;externalUpdateLimitsCard&#x60; 
   * @return resourceIds
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<String> getResourceIds() {
        return resourceIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RESOURCE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getResourceIds_JsonNullable() {
    return resourceIds;
  }
  
  @JsonProperty(JSON_PROPERTY_RESOURCE_IDS)
  public void setResourceIds_JsonNullable(JsonNullable<List<String>> resourceIds) {
    this.resourceIds = resourceIds;
  }

  public void setResourceIds(@javax.annotation.Nullable List<String> resourceIds) {
    this.resourceIds = JsonNullable.<List<String>>of(resourceIds);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostExtOperationRequest postExtOperationRequest = (PostExtOperationRequest) o;
    return Objects.equals(this.actionName, postExtOperationRequest.actionName) &&
        equalsNullable(this.scaProof, postExtOperationRequest.scaProof) &&
        Objects.equals(this.actionDate, postExtOperationRequest.actionDate) &&
        equalsNullable(this.resourceIds, postExtOperationRequest.resourceIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionName, hashCodeNullable(scaProof), actionDate, hashCodeNullable(resourceIds));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostExtOperationRequest {\n");
    sb.append("    actionName: ").append(toIndentedString(actionName)).append("\n");
    sb.append("    scaProof: ").append(toIndentedString(scaProof)).append("\n");
    sb.append("    actionDate: ").append(toIndentedString(actionDate)).append("\n");
    sb.append("    resourceIds: ").append(toIndentedString(resourceIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

