/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostKycliveness201ResponseUserKycInner
 */
@JsonPropertyOrder({
  PostKycliveness201ResponseUserKycInner.JSON_PROPERTY_IDENTIFICATION_ID,
  PostKycliveness201ResponseUserKycInner.JSON_PROPERTY_IDENTIFICATION_URL
})
@JsonTypeName("postKycliveness_201_response_user_kyc_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class PostKycliveness201ResponseUserKycInner {
  public static final String JSON_PROPERTY_IDENTIFICATION_ID = "identification-id";
  @javax.annotation.Nullable
  private String identificationId;

  public static final String JSON_PROPERTY_IDENTIFICATION_URL = "identification-url";
  @javax.annotation.Nullable
  private String identificationUrl;

  public PostKycliveness201ResponseUserKycInner() {
  }

  public PostKycliveness201ResponseUserKycInner identificationId(@javax.annotation.Nullable String identificationId) {
    
    this.identificationId = identificationId;
    return this;
  }

  /**
   * Get identificationId
   * @return identificationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificationId() {
    return identificationId;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationId(@javax.annotation.Nullable String identificationId) {
    this.identificationId = identificationId;
  }

  public PostKycliveness201ResponseUserKycInner identificationUrl(@javax.annotation.Nullable String identificationUrl) {
    
    this.identificationUrl = identificationUrl;
    return this;
  }

  /**
   * Get identificationUrl
   * @return identificationUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificationUrl() {
    return identificationUrl;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFICATION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificationUrl(@javax.annotation.Nullable String identificationUrl) {
    this.identificationUrl = identificationUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostKycliveness201ResponseUserKycInner postKycliveness201ResponseUserKycInner = (PostKycliveness201ResponseUserKycInner) o;
    return Objects.equals(this.identificationId, postKycliveness201ResponseUserKycInner.identificationId) &&
        Objects.equals(this.identificationUrl, postKycliveness201ResponseUserKycInner.identificationUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationId, identificationUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostKycliveness201ResponseUserKycInner {\n");
    sb.append("    identificationId: ").append(toIndentedString(identificationId)).append("\n");
    sb.append("    identificationUrl: ").append(toIndentedString(identificationUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

