/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PostPayinRequest
 */
@JsonPropertyOrder({
  PostPayinRequest.JSON_PROPERTY_PAYIN_TAG,
  PostPayinRequest.JSON_PROPERTY_ACCESS_TAG,
  PostPayinRequest.JSON_PROPERTY_WALLET_ID,
  PostPayinRequest.JSON_PROPERTY_USER_ID,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_METHOD_ID,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_ACCEPTED_URL,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_WAITING_URL,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_CANCELED_URL,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_REFUSED_URL,
  PostPayinRequest.JSON_PROPERTY_PAYMENT_EXCEPTION_URL,
  PostPayinRequest.JSON_PROPERTY_AMOUNT,
  PostPayinRequest.JSON_PROPERTY_DISTRIBUTOR_FEE,
  PostPayinRequest.JSON_PROPERTY_CURRENCY,
  PostPayinRequest.JSON_PROPERTY_MESSAGE_TO_USER,
  PostPayinRequest.JSON_PROPERTY_LANGUAGE,
  PostPayinRequest.JSON_PROPERTY_CREATED_IP,
  PostPayinRequest.JSON_PROPERTY_PAYIN_DATE,
  PostPayinRequest.JSON_PROPERTY_MANDATE_ID
})
@JsonTypeName("postPayin_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class PostPayinRequest {
  public static final String JSON_PROPERTY_PAYIN_TAG = "payinTag";
  @javax.annotation.Nullable
  private String payinTag;

  public static final String JSON_PROPERTY_ACCESS_TAG = "accessTag";
  @javax.annotation.Nullable
  private String accessTag;

  public static final String JSON_PROPERTY_WALLET_ID = "walletId";
  @javax.annotation.Nonnull
  private Integer walletId;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nonnull
  private String userId;

  /**
   * The type of payin.  | Id | Payment by | | ---| --- | | &#x60;20&#x60; | [Received SEPA Credit Transfer (SCTR)](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr). You can only create such payins in Sandbox, otherwise created automatically upon receiving a transfer. | | &#x60;21&#x60; | [Emitted SEPA Direct Debit (SDDE)](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde). | | &#x60;23&#x60; | Full Hosted HTML Payment Form. If you use this &#x60;paymentMethodId&#x60;, the &#x60;paymentAcceptedUrl&#x60;, &#x60;paymentRefusedUrl&#x60;, &#x60;paymentWaitingUrl&#x60;, &#x60;paymentCanceledUrl&#x60; and &#x60;paymentExceptionUrl&#x60; fields are mandatory. CSS of the payment page can be customized. | | &#x60;24&#x60; | IFrame Payment Form. Please note that if you use this &#x60;paymentMethodId&#x60;, the &#x60;paymentAcceptedUrl&#x60;, &#x60;paymentRefusedUrl&#x60;, &#x60;paymentWaitingUrl&#x60;, &#x60;paymentCanceledUrl&#x60; and &#x60;paymentExceptionUrl&#x60; fields are mandatory. CSS of the payment page can be customized. | | &#x60;25&#x60; | [Card topups](/guide/acquiring/introduction.html). You cannot create a payin directly with this method id. The payin will be automatically created by Treezor. | | &#x60;26&#x60; | [Check cashing](/guide/cheques/introduction.html) | | &#x60;27&#x60; | [Received SEPA Instant Credit Transfer](/guide/transfers/credit-transfer-inst.html#received-instant-credit-transfers-sctr-inst). You cannot create a payin directly with this method id. The payin will be automatically created by Treezor. | 
   */
  public enum PaymentMethodIdEnum {
    _20(String.valueOf("20")),
    
    _21(String.valueOf("21")),
    
    _23(String.valueOf("23")),
    
    _24(String.valueOf("24")),
    
    _25(String.valueOf("25")),
    
    _26(String.valueOf("26")),
    
    _27(String.valueOf("27"));

    private String value;

    PaymentMethodIdEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentMethodIdEnum fromValue(String value) {
      for (PaymentMethodIdEnum b : PaymentMethodIdEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_METHOD_ID = "paymentMethodId";
  @javax.annotation.Nonnull
  private PaymentMethodIdEnum paymentMethodId;

  public static final String JSON_PROPERTY_PAYMENT_ACCEPTED_URL = "paymentAcceptedUrl";
  @javax.annotation.Nullable
  private String paymentAcceptedUrl;

  public static final String JSON_PROPERTY_PAYMENT_WAITING_URL = "paymentWaitingUrl";
  @javax.annotation.Nullable
  private String paymentWaitingUrl;

  public static final String JSON_PROPERTY_PAYMENT_CANCELED_URL = "paymentCanceledUrl";
  @javax.annotation.Nullable
  private String paymentCanceledUrl;

  public static final String JSON_PROPERTY_PAYMENT_REFUSED_URL = "paymentRefusedUrl";
  @javax.annotation.Nullable
  private String paymentRefusedUrl;

  public static final String JSON_PROPERTY_PAYMENT_EXCEPTION_URL = "paymentExceptionUrl";
  @javax.annotation.Nullable
  private String paymentExceptionUrl;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Float amount;

  public static final String JSON_PROPERTY_DISTRIBUTOR_FEE = "distributorFee";
  @javax.annotation.Nullable
  private Float distributorFee;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_MESSAGE_TO_USER = "messageToUser";
  @javax.annotation.Nullable
  private String messageToUser;

  /**
   * Language for the third party interface.
   */
  public enum LanguageEnum {
    FRA(String.valueOf("FRA")),
    
    GBR(String.valueOf("GBR")),
    
    ESP(String.valueOf("ESP")),
    
    ITA(String.valueOf("ITA")),
    
    PRT(String.valueOf("PRT"));

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LanguageEnum fromValue(String value) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  @javax.annotation.Nullable
  private LanguageEnum language;

  public static final String JSON_PROPERTY_CREATED_IP = "createdIp";
  @javax.annotation.Nullable
  private String createdIp;

  public static final String JSON_PROPERTY_PAYIN_DATE = "payinDate";
  @javax.annotation.Nullable
  private String payinDate;

  public static final String JSON_PROPERTY_MANDATE_ID = "mandateId";
  @javax.annotation.Nullable
  private Integer mandateId;

  public PostPayinRequest() {
  }

  public PostPayinRequest payinTag(@javax.annotation.Nullable String payinTag) {
    
    this.payinTag = payinTag;
    return this;
  }

  /**
   * Custom attribute to use as you see fit. Learn more in the [Object tags](/guide/api-basics/objects-tags.html#objects-tags) article.  Format: hc characters and &#x60;/&#x60; &#x60;!&#x60; &#x60;-&#x60; &#x60;_&#x60; &#x60;.&#x60; &#x60;*&#x60; &#x60;&#39;&#x60; &#x60;(&#x60; &#x60;)&#x60; 
   * @return payinTag
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYIN_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayinTag() {
    return payinTag;
  }


  @JsonProperty(JSON_PROPERTY_PAYIN_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinTag(@javax.annotation.Nullable String payinTag) {
    this.payinTag = payinTag;
  }

  public PostPayinRequest accessTag(@javax.annotation.Nullable String accessTag) {
    
    this.accessTag = accessTag;
    return this;
  }

  /**
   * A unique identifier used to enforce [Idempotency](/guide/api-basics/idempotency.html). 
   * @return accessTag
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessTag() {
    return accessTag;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessTag(@javax.annotation.Nullable String accessTag) {
    this.accessTag = accessTag;
  }

  public PostPayinRequest walletId(@javax.annotation.Nonnull Integer walletId) {
    
    this.walletId = walletId;
    return this;
  }

  /**
   * The unique identifier of the credited Wallet.
   * @return walletId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WALLET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWalletId() {
    return walletId;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWalletId(@javax.annotation.Nonnull Integer walletId) {
    this.walletId = walletId;
  }

  public PostPayinRequest userId(@javax.annotation.Nonnull String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * The unique identifier of the User making the payin.  Note that for the &#x60;paymentMethodId&#x60; of &#x60;21&#x60; and &#x60;26&#x60;, you don&#39;t need to provide this value. It will be set automatically by Treezor. 
   * @return userId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@javax.annotation.Nonnull String userId) {
    this.userId = userId;
  }

  public PostPayinRequest paymentMethodId(@javax.annotation.Nonnull PaymentMethodIdEnum paymentMethodId) {
    
    this.paymentMethodId = paymentMethodId;
    return this;
  }

  /**
   * The type of payin.  | Id | Payment by | | ---| --- | | &#x60;20&#x60; | [Received SEPA Credit Transfer (SCTR)](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr). You can only create such payins in Sandbox, otherwise created automatically upon receiving a transfer. | | &#x60;21&#x60; | [Emitted SEPA Direct Debit (SDDE)](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde). | | &#x60;23&#x60; | Full Hosted HTML Payment Form. If you use this &#x60;paymentMethodId&#x60;, the &#x60;paymentAcceptedUrl&#x60;, &#x60;paymentRefusedUrl&#x60;, &#x60;paymentWaitingUrl&#x60;, &#x60;paymentCanceledUrl&#x60; and &#x60;paymentExceptionUrl&#x60; fields are mandatory. CSS of the payment page can be customized. | | &#x60;24&#x60; | IFrame Payment Form. Please note that if you use this &#x60;paymentMethodId&#x60;, the &#x60;paymentAcceptedUrl&#x60;, &#x60;paymentRefusedUrl&#x60;, &#x60;paymentWaitingUrl&#x60;, &#x60;paymentCanceledUrl&#x60; and &#x60;paymentExceptionUrl&#x60; fields are mandatory. CSS of the payment page can be customized. | | &#x60;25&#x60; | [Card topups](/guide/acquiring/introduction.html). You cannot create a payin directly with this method id. The payin will be automatically created by Treezor. | | &#x60;26&#x60; | [Check cashing](/guide/cheques/introduction.html) | | &#x60;27&#x60; | [Received SEPA Instant Credit Transfer](/guide/transfers/credit-transfer-inst.html#received-instant-credit-transfers-sctr-inst). You cannot create a payin directly with this method id. The payin will be automatically created by Treezor. | 
   * @return paymentMethodId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentMethodIdEnum getPaymentMethodId() {
    return paymentMethodId;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentMethodId(@javax.annotation.Nonnull PaymentMethodIdEnum paymentMethodId) {
    this.paymentMethodId = paymentMethodId;
  }

  public PostPayinRequest paymentAcceptedUrl(@javax.annotation.Nullable String paymentAcceptedUrl) {
    
    this.paymentAcceptedUrl = paymentAcceptedUrl;
    return this;
  }

  /**
   * URL to which the cardholder is redirected if payment is successful. When using &#x60;paymentMethodId&#x60; &#x60;23&#x60; and &#x60;24&#x60; an HTTPS URL is mandatory. 
   * @return paymentAcceptedUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_ACCEPTED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentAcceptedUrl() {
    return paymentAcceptedUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_ACCEPTED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentAcceptedUrl(@javax.annotation.Nullable String paymentAcceptedUrl) {
    this.paymentAcceptedUrl = paymentAcceptedUrl;
  }

  public PostPayinRequest paymentWaitingUrl(@javax.annotation.Nullable String paymentWaitingUrl) {
    
    this.paymentWaitingUrl = paymentWaitingUrl;
    return this;
  }

  /**
   * URL to which the cardholder is redirected to wait payment processing. When using &#x60;paymentMethodId&#x60; &#x60;23&#x60; and &#x60;24&#x60; an HTTPS URL is mandatory. 
   * @return paymentWaitingUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_WAITING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentWaitingUrl() {
    return paymentWaitingUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_WAITING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentWaitingUrl(@javax.annotation.Nullable String paymentWaitingUrl) {
    this.paymentWaitingUrl = paymentWaitingUrl;
  }

  public PostPayinRequest paymentCanceledUrl(@javax.annotation.Nullable String paymentCanceledUrl) {
    
    this.paymentCanceledUrl = paymentCanceledUrl;
    return this;
  }

  /**
   * URL to which the cardholder is redirected if payment is canceled. When using &#x60;paymentMethodId&#x60; &#x60;23&#x60; and &#x60;24&#x60; an HTTPS URL is mandatory. 
   * @return paymentCanceledUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_CANCELED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentCanceledUrl() {
    return paymentCanceledUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_CANCELED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentCanceledUrl(@javax.annotation.Nullable String paymentCanceledUrl) {
    this.paymentCanceledUrl = paymentCanceledUrl;
  }

  public PostPayinRequest paymentRefusedUrl(@javax.annotation.Nullable String paymentRefusedUrl) {
    
    this.paymentRefusedUrl = paymentRefusedUrl;
    return this;
  }

  /**
   * URL to which the cardholder is redirected if payment is refused. When using &#x60;paymentMethodId&#x60; &#x60;23&#x60; and &#x60;24&#x60; an HTTPS URL is mandatory. 
   * @return paymentRefusedUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_REFUSED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentRefusedUrl() {
    return paymentRefusedUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_REFUSED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentRefusedUrl(@javax.annotation.Nullable String paymentRefusedUrl) {
    this.paymentRefusedUrl = paymentRefusedUrl;
  }

  public PostPayinRequest paymentExceptionUrl(@javax.annotation.Nullable String paymentExceptionUrl) {
    
    this.paymentExceptionUrl = paymentExceptionUrl;
    return this;
  }

  /**
   * URL to which the cardholder is redirected if the payment process raised an exception. When using &#x60;paymentMethodId&#x60; &#x60;23&#x60; and &#x60;24&#x60; an HTTPS URL is mandatory. 
   * @return paymentExceptionUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_EXCEPTION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentExceptionUrl() {
    return paymentExceptionUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_EXCEPTION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentExceptionUrl(@javax.annotation.Nullable String paymentExceptionUrl) {
    this.paymentExceptionUrl = paymentExceptionUrl;
  }

  public PostPayinRequest amount(@javax.annotation.Nonnull Float amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * The amount of the payin.
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Float getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Float amount) {
    this.amount = amount;
  }

  public PostPayinRequest distributorFee(@javax.annotation.Nullable Float distributorFee) {
    
    this.distributorFee = distributorFee;
    return this;
  }

  /**
   * Get distributorFee
   * @return distributorFee
   * @deprecated
   */
  @Deprecated
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTRIBUTOR_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDistributorFee() {
    return distributorFee;
  }


  @JsonProperty(JSON_PROPERTY_DISTRIBUTOR_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistributorFee(@javax.annotation.Nullable Float distributorFee) {
    this.distributorFee = distributorFee;
  }

  public PostPayinRequest currency(@javax.annotation.Nonnull String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * The currency of the payin in [ISO 4217](/guide/api-basics/data-format.html#currencies) format. Must be the same as the Wallet currency. 
   * @return currency
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }

  public PostPayinRequest messageToUser(@javax.annotation.Nullable String messageToUser) {
    
    this.messageToUser = messageToUser;
    return this;
  }

  /**
   * Message to send to Wallet of the user. For SEPA Direct Debit Core payment method, this parameter reconciles information transmitted to the Debtor (i.e., Invoice number). In this case, it can&#39;t exceed 140 characters.
   * @return messageToUser
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE_TO_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessageToUser() {
    return messageToUser;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE_TO_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessageToUser(@javax.annotation.Nullable String messageToUser) {
    this.messageToUser = messageToUser;
  }

  public PostPayinRequest language(@javax.annotation.Nullable LanguageEnum language) {
    
    this.language = language;
    return this;
  }

  /**
   * Language for the third party interface.
   * @return language
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LanguageEnum getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(@javax.annotation.Nullable LanguageEnum language) {
    this.language = language;
  }

  public PostPayinRequest createdIp(@javax.annotation.Nullable String createdIp) {
    
    this.createdIp = createdIp;
    return this;
  }

  /**
   * The IP address of the User.
   * @return createdIp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedIp() {
    return createdIp;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedIp(@javax.annotation.Nullable String createdIp) {
    this.createdIp = createdIp;
  }

  public PostPayinRequest payinDate(@javax.annotation.Nullable String payinDate) {
    
    this.payinDate = payinDate;
    return this;
  }

  /**
   * The date at which the SDD should be presented.   In the case of SDD Core, this parameter defaults to the third working day following the payin creation if left empty.   Format: &#x60;YYYY-MM-DD&#x60;, a [SEPA Open Banking Day](/guide/overview/glossary.html#sepa-open-banking-days) is expected, based on the rules described in the [dedicated article](/guide/transfers/direct-debit.html#parameters). 
   * @return payinDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYIN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayinDate() {
    return payinDate;
  }


  @JsonProperty(JSON_PROPERTY_PAYIN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayinDate(@javax.annotation.Nullable String payinDate) {
    this.payinDate = payinDate;
  }

  public PostPayinRequest mandateId(@javax.annotation.Nullable Integer mandateId) {
    
    this.mandateId = mandateId;
    return this;
  }

  /**
   * The unique identifier of the Mandate. This parameter is mandatory when performing a payin with method SDD Core.
   * @return mandateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANDATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMandateId() {
    return mandateId;
  }


  @JsonProperty(JSON_PROPERTY_MANDATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMandateId(@javax.annotation.Nullable Integer mandateId) {
    this.mandateId = mandateId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostPayinRequest postPayinRequest = (PostPayinRequest) o;
    return Objects.equals(this.payinTag, postPayinRequest.payinTag) &&
        Objects.equals(this.accessTag, postPayinRequest.accessTag) &&
        Objects.equals(this.walletId, postPayinRequest.walletId) &&
        Objects.equals(this.userId, postPayinRequest.userId) &&
        Objects.equals(this.paymentMethodId, postPayinRequest.paymentMethodId) &&
        Objects.equals(this.paymentAcceptedUrl, postPayinRequest.paymentAcceptedUrl) &&
        Objects.equals(this.paymentWaitingUrl, postPayinRequest.paymentWaitingUrl) &&
        Objects.equals(this.paymentCanceledUrl, postPayinRequest.paymentCanceledUrl) &&
        Objects.equals(this.paymentRefusedUrl, postPayinRequest.paymentRefusedUrl) &&
        Objects.equals(this.paymentExceptionUrl, postPayinRequest.paymentExceptionUrl) &&
        Objects.equals(this.amount, postPayinRequest.amount) &&
        Objects.equals(this.distributorFee, postPayinRequest.distributorFee) &&
        Objects.equals(this.currency, postPayinRequest.currency) &&
        Objects.equals(this.messageToUser, postPayinRequest.messageToUser) &&
        Objects.equals(this.language, postPayinRequest.language) &&
        Objects.equals(this.createdIp, postPayinRequest.createdIp) &&
        Objects.equals(this.payinDate, postPayinRequest.payinDate) &&
        Objects.equals(this.mandateId, postPayinRequest.mandateId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payinTag, accessTag, walletId, userId, paymentMethodId, paymentAcceptedUrl, paymentWaitingUrl, paymentCanceledUrl, paymentRefusedUrl, paymentExceptionUrl, amount, distributorFee, currency, messageToUser, language, createdIp, payinDate, mandateId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostPayinRequest {\n");
    sb.append("    payinTag: ").append(toIndentedString(payinTag)).append("\n");
    sb.append("    accessTag: ").append(toIndentedString(accessTag)).append("\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    paymentMethodId: ").append(toIndentedString(paymentMethodId)).append("\n");
    sb.append("    paymentAcceptedUrl: ").append(toIndentedString(paymentAcceptedUrl)).append("\n");
    sb.append("    paymentWaitingUrl: ").append(toIndentedString(paymentWaitingUrl)).append("\n");
    sb.append("    paymentCanceledUrl: ").append(toIndentedString(paymentCanceledUrl)).append("\n");
    sb.append("    paymentRefusedUrl: ").append(toIndentedString(paymentRefusedUrl)).append("\n");
    sb.append("    paymentExceptionUrl: ").append(toIndentedString(paymentExceptionUrl)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    distributorFee: ").append(toIndentedString(distributorFee)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    messageToUser: ").append(toIndentedString(messageToUser)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    createdIp: ").append(toIndentedString(createdIp)).append("\n");
    sb.append("    payinDate: ").append(toIndentedString(payinDate)).append("\n");
    sb.append("    mandateId: ").append(toIndentedString(mandateId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

