/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PutCardRequest
 */
@JsonPropertyOrder({
  PutCardRequest.JSON_PROPERTY_MCC_RESTRICTION_GROUP_ID,
  PutCardRequest.JSON_PROPERTY_MERCHANT_RESTRICTION_GROUP_ID,
  PutCardRequest.JSON_PROPERTY_COUNTRY_RESTRICTION_GROUP_ID,
  PutCardRequest.JSON_PROPERTY_ACCESS_TAG,
  PutCardRequest.JSON_PROPERTY_CARD_TAG
})
@JsonTypeName("putCard_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class PutCardRequest {
  public static final String JSON_PROPERTY_MCC_RESTRICTION_GROUP_ID = "mccRestrictionGroupId";
  @javax.annotation.Nullable
  private Integer mccRestrictionGroupId;

  public static final String JSON_PROPERTY_MERCHANT_RESTRICTION_GROUP_ID = "merchantRestrictionGroupId";
  @javax.annotation.Nullable
  private Integer merchantRestrictionGroupId;

  public static final String JSON_PROPERTY_COUNTRY_RESTRICTION_GROUP_ID = "countryRestrictionGroupId";
  @javax.annotation.Nullable
  private Integer countryRestrictionGroupId;

  public static final String JSON_PROPERTY_ACCESS_TAG = "accessTag";
  @javax.annotation.Nullable
  private String accessTag;

  public static final String JSON_PROPERTY_CARD_TAG = "cardTag";
  @javax.annotation.Nullable
  private String cardTag;

  public PutCardRequest() {
  }

  public PutCardRequest mccRestrictionGroupId(@javax.annotation.Nullable Integer mccRestrictionGroupId) {
    
    this.mccRestrictionGroupId = mccRestrictionGroupId;
    return this;
  }

  /**
   * The merchant category restriction group (&#x60;mccRestrictionGroup&#x60;) to apply to the card. 
   * @return mccRestrictionGroupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MCC_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMccRestrictionGroupId() {
    return mccRestrictionGroupId;
  }


  @JsonProperty(JSON_PROPERTY_MCC_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMccRestrictionGroupId(@javax.annotation.Nullable Integer mccRestrictionGroupId) {
    this.mccRestrictionGroupId = mccRestrictionGroupId;
  }

  public PutCardRequest merchantRestrictionGroupId(@javax.annotation.Nullable Integer merchantRestrictionGroupId) {
    
    this.merchantRestrictionGroupId = merchantRestrictionGroupId;
    return this;
  }

  /**
   * The merchant Id restriction group (&#x60;merchantRestrictionGroupId&#x60;) to apply to the card. 
   * @return merchantRestrictionGroupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MERCHANT_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMerchantRestrictionGroupId() {
    return merchantRestrictionGroupId;
  }


  @JsonProperty(JSON_PROPERTY_MERCHANT_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMerchantRestrictionGroupId(@javax.annotation.Nullable Integer merchantRestrictionGroupId) {
    this.merchantRestrictionGroupId = merchantRestrictionGroupId;
  }

  public PutCardRequest countryRestrictionGroupId(@javax.annotation.Nullable Integer countryRestrictionGroupId) {
    
    this.countryRestrictionGroupId = countryRestrictionGroupId;
    return this;
  }

  /**
   * The country restriction group (&#x60;countryRestrictionGroupId&#x60;) to apply to the card. 
   * @return countryRestrictionGroupId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCountryRestrictionGroupId() {
    return countryRestrictionGroupId;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_RESTRICTION_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryRestrictionGroupId(@javax.annotation.Nullable Integer countryRestrictionGroupId) {
    this.countryRestrictionGroupId = countryRestrictionGroupId;
  }

  public PutCardRequest accessTag(@javax.annotation.Nullable String accessTag) {
    
    this.accessTag = accessTag;
    return this;
  }

  /**
   * A unique identifier used to enforce [Idempotency](/guide/api-basics/idempotency.html). 
   * @return accessTag
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessTag() {
    return accessTag;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessTag(@javax.annotation.Nullable String accessTag) {
    this.accessTag = accessTag;
  }

  public PutCardRequest cardTag(@javax.annotation.Nullable String cardTag) {
    
    this.cardTag = cardTag;
    return this;
  }

  /**
   * Custom attribute to use as you see fit. Learn more in the [Object tags](/guide/api-basics/objects-tags.html#objects-tags) article.  Format: hc characters and &#x60;/&#x60; &#x60;!&#x60; &#x60;-&#x60; &#x60;_&#x60; &#x60;.&#x60; &#x60;*&#x60; &#x60;&#39;&#x60; &#x60;(&#x60; &#x60;)&#x60; 
   * @return cardTag
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARD_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCardTag() {
    return cardTag;
  }


  @JsonProperty(JSON_PROPERTY_CARD_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardTag(@javax.annotation.Nullable String cardTag) {
    this.cardTag = cardTag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutCardRequest putCardRequest = (PutCardRequest) o;
    return Objects.equals(this.mccRestrictionGroupId, putCardRequest.mccRestrictionGroupId) &&
        Objects.equals(this.merchantRestrictionGroupId, putCardRequest.merchantRestrictionGroupId) &&
        Objects.equals(this.countryRestrictionGroupId, putCardRequest.countryRestrictionGroupId) &&
        Objects.equals(this.accessTag, putCardRequest.accessTag) &&
        Objects.equals(this.cardTag, putCardRequest.cardTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mccRestrictionGroupId, merchantRestrictionGroupId, countryRestrictionGroupId, accessTag, cardTag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutCardRequest {\n");
    sb.append("    mccRestrictionGroupId: ").append(toIndentedString(mccRestrictionGroupId)).append("\n");
    sb.append("    merchantRestrictionGroupId: ").append(toIndentedString(merchantRestrictionGroupId)).append("\n");
    sb.append("    countryRestrictionGroupId: ").append(toIndentedString(countryRestrictionGroupId)).append("\n");
    sb.append("    accessTag: ").append(toIndentedString(accessTag)).append("\n");
    sb.append("    cardTag: ").append(toIndentedString(cardTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

