/*
 * Copyright 2025 Firefly Software Solutions Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReadcardDigitalizations200ResponseCardDigitalizationsInner
 */
@JsonPropertyOrder({
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_ID,
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_CARD_ID,
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_EXTERNAL_ID,
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_STATUS,
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_CREATED_DATE,
  ReadcardDigitalizations200ResponseCardDigitalizationsInner.JSON_PROPERTY_MODIFIED_DATE
})
@JsonTypeName("readcardDigitalizations_200_response_cardDigitalizations_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class ReadcardDigitalizations200ResponseCardDigitalizationsInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_CARD_ID = "cardId";
  @javax.annotation.Nullable
  private String cardId;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  @javax.annotation.Nullable
  private Integer externalId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @javax.annotation.Nullable
  private String createdDate;

  public static final String JSON_PROPERTY_MODIFIED_DATE = "modifiedDate";
  @javax.annotation.Nullable
  private String modifiedDate;

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner() {
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner id(@javax.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner cardId(@javax.annotation.Nullable String cardId) {
    
    this.cardId = cardId;
    return this;
  }

  /**
   * Get cardId
   * @return cardId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CARD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCardId() {
    return cardId;
  }


  @JsonProperty(JSON_PROPERTY_CARD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardId(@javax.annotation.Nullable String cardId) {
    this.cardId = cardId;
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner externalId(@javax.annotation.Nullable Integer externalId) {
    
    this.externalId = externalId;
    return this;
  }

  /**
   * Get externalId
   * @return externalId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getExternalId() {
    return externalId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalId(@javax.annotation.Nullable Integer externalId) {
    this.externalId = externalId;
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * | Status | Description | | ---- | ----------- | | A | Active | | U | Not tokenized | | S | Suspended | | D (or X) | Deactivated (Final status, cannot be changed)| 
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner createdDate(@javax.annotation.Nullable String createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Get createdDate
   * @return createdDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedDate() {
    return createdDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDate(@javax.annotation.Nullable String createdDate) {
    this.createdDate = createdDate;
  }

  public ReadcardDigitalizations200ResponseCardDigitalizationsInner modifiedDate(@javax.annotation.Nullable String modifiedDate) {
    
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * Get modifiedDate
   * @return modifiedDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModifiedDate() {
    return modifiedDate;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModifiedDate(@javax.annotation.Nullable String modifiedDate) {
    this.modifiedDate = modifiedDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadcardDigitalizations200ResponseCardDigitalizationsInner readcardDigitalizations200ResponseCardDigitalizationsInner = (ReadcardDigitalizations200ResponseCardDigitalizationsInner) o;
    return Objects.equals(this.id, readcardDigitalizations200ResponseCardDigitalizationsInner.id) &&
        Objects.equals(this.cardId, readcardDigitalizations200ResponseCardDigitalizationsInner.cardId) &&
        Objects.equals(this.externalId, readcardDigitalizations200ResponseCardDigitalizationsInner.externalId) &&
        Objects.equals(this.status, readcardDigitalizations200ResponseCardDigitalizationsInner.status) &&
        Objects.equals(this.createdDate, readcardDigitalizations200ResponseCardDigitalizationsInner.createdDate) &&
        Objects.equals(this.modifiedDate, readcardDigitalizations200ResponseCardDigitalizationsInner.modifiedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, cardId, externalId, status, createdDate, modifiedDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadcardDigitalizations200ResponseCardDigitalizationsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cardId: ").append(toIndentedString(cardId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

