/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SimulateCardTransactions201ResponseInner
 */
@JsonPropertyOrder({
  SimulateCardTransactions201ResponseInner.JSON_PROPERTY_NUMBER,
  SimulateCardTransactions201ResponseInner.JSON_PROPERTY_PUBLIC_TOKEN
})
@JsonTypeName("simulateCardTransactions_201_response_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class SimulateCardTransactions201ResponseInner {
  public static final String JSON_PROPERTY_NUMBER = "number";
  @javax.annotation.Nullable
  private Integer number;

  public static final String JSON_PROPERTY_PUBLIC_TOKEN = "publicToken";
  @javax.annotation.Nullable
  private String publicToken;

  public SimulateCardTransactions201ResponseInner() {
  }

  public SimulateCardTransactions201ResponseInner number(@javax.annotation.Nullable Integer number) {
    
    this.number = number;
    return this;
  }

  /**
   * Get number
   * @return number
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumber() {
    return number;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumber(@javax.annotation.Nullable Integer number) {
    this.number = number;
  }

  public SimulateCardTransactions201ResponseInner publicToken(@javax.annotation.Nullable String publicToken) {
    
    this.publicToken = publicToken;
    return this;
  }

  /**
   * Get publicToken
   * @return publicToken
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicToken() {
    return publicToken;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicToken(@javax.annotation.Nullable String publicToken) {
    this.publicToken = publicToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimulateCardTransactions201ResponseInner simulateCardTransactions201ResponseInner = (SimulateCardTransactions201ResponseInner) o;
    return Objects.equals(this.number, simulateCardTransactions201ResponseInner.number) &&
        Objects.equals(this.publicToken, simulateCardTransactions201ResponseInner.publicToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, publicToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimulateCardTransactions201ResponseInner {\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    publicToken: ").append(toIndentedString(publicToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

