/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StatementPayoutRefund
 */
@JsonPropertyOrder({
  StatementPayoutRefund.JSON_PROPERTY_PAYOUT_REFUND_ID,
  StatementPayoutRefund.JSON_PROPERTY_PAYOUT_ID,
  StatementPayoutRefund.JSON_PROPERTY_PAYOUT_TAG,
  StatementPayoutRefund.JSON_PROPERTY_LABEL,
  StatementPayoutRefund.JSON_PROPERTY_BENEFICIARY_ID,
  StatementPayoutRefund.JSON_PROPERTY_BENEFICIARY_NAME,
  StatementPayoutRefund.JSON_PROPERTY_END_TO_END_ID,
  StatementPayoutRefund.JSON_PROPERTY_REASON_CODE,
  StatementPayoutRefund.JSON_PROPERTY_REASON_DESCRIPTION,
  StatementPayoutRefund.JSON_PROPERTY_UNIQUE_MANDATE_REFERENCE
})
@JsonTypeName("statementPayoutRefund")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class StatementPayoutRefund {
  public static final String JSON_PROPERTY_PAYOUT_REFUND_ID = "payoutRefundId";
  @javax.annotation.Nullable
  private String payoutRefundId;

  public static final String JSON_PROPERTY_PAYOUT_ID = "payoutId";
  @javax.annotation.Nullable
  private String payoutId;

  public static final String JSON_PROPERTY_PAYOUT_TAG = "payoutTag";
  @javax.annotation.Nullable
  private JsonNullable<String> payoutTag = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nullable
  private JsonNullable<String> label = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BENEFICIARY_ID = "beneficiaryId";
  @javax.annotation.Nullable
  private String beneficiaryId;

  public static final String JSON_PROPERTY_BENEFICIARY_NAME = "beneficiaryName";
  @javax.annotation.Nullable
  private JsonNullable<String> beneficiaryName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_END_TO_END_ID = "endToEndId";
  @javax.annotation.Nullable
  private JsonNullable<String> endToEndId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_REASON_CODE = "reasonCode";
  @javax.annotation.Nullable
  private JsonNullable<String> reasonCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_REASON_DESCRIPTION = "reasonDescription";
  @javax.annotation.Nullable
  private JsonNullable<String> reasonDescription = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_UNIQUE_MANDATE_REFERENCE = "uniqueMandateReference";
  @javax.annotation.Nullable
  private JsonNullable<String> uniqueMandateReference = JsonNullable.<String>undefined();

  public StatementPayoutRefund() {
  }

  public StatementPayoutRefund payoutRefundId(@javax.annotation.Nullable String payoutRefundId) {
    
    this.payoutRefundId = payoutRefundId;
    return this;
  }

  /**
   * Get payoutRefundId
   * @return payoutRefundId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_REFUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayoutRefundId() {
    return payoutRefundId;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_REFUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutRefundId(@javax.annotation.Nullable String payoutRefundId) {
    this.payoutRefundId = payoutRefundId;
  }

  public StatementPayoutRefund payoutId(@javax.annotation.Nullable String payoutId) {
    
    this.payoutId = payoutId;
    return this;
  }

  /**
   * Get payoutId
   * @return payoutId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYOUT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayoutId() {
    return payoutId;
  }


  @JsonProperty(JSON_PROPERTY_PAYOUT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayoutId(@javax.annotation.Nullable String payoutId) {
    this.payoutId = payoutId;
  }

  public StatementPayoutRefund payoutTag(@javax.annotation.Nullable String payoutTag) {
    this.payoutTag = JsonNullable.<String>of(payoutTag);
    
    return this;
  }

  /**
   * Get payoutTag
   * @return payoutTag
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPayoutTag() {
        return payoutTag.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PAYOUT_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPayoutTag_JsonNullable() {
    return payoutTag;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYOUT_TAG)
  public void setPayoutTag_JsonNullable(JsonNullable<String> payoutTag) {
    this.payoutTag = payoutTag;
  }

  public void setPayoutTag(@javax.annotation.Nullable String payoutTag) {
    this.payoutTag = JsonNullable.<String>of(payoutTag);
  }

  public StatementPayoutRefund label(@javax.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
    
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLabel() {
        return label.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLabel_JsonNullable() {
    return label;
  }
  
  @JsonProperty(JSON_PROPERTY_LABEL)
  public void setLabel_JsonNullable(JsonNullable<String> label) {
    this.label = label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
  }

  public StatementPayoutRefund beneficiaryId(@javax.annotation.Nullable String beneficiaryId) {
    
    this.beneficiaryId = beneficiaryId;
    return this;
  }

  /**
   * Get beneficiaryId
   * @return beneficiaryId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeneficiaryId() {
    return beneficiaryId;
  }


  @JsonProperty(JSON_PROPERTY_BENEFICIARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeneficiaryId(@javax.annotation.Nullable String beneficiaryId) {
    this.beneficiaryId = beneficiaryId;
  }

  public StatementPayoutRefund beneficiaryName(@javax.annotation.Nullable String beneficiaryName) {
    this.beneficiaryName = JsonNullable.<String>of(beneficiaryName);
    
    return this;
  }

  /**
   * Get beneficiaryName
   * @return beneficiaryName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getBeneficiaryName() {
        return beneficiaryName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BENEFICIARY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBeneficiaryName_JsonNullable() {
    return beneficiaryName;
  }
  
  @JsonProperty(JSON_PROPERTY_BENEFICIARY_NAME)
  public void setBeneficiaryName_JsonNullable(JsonNullable<String> beneficiaryName) {
    this.beneficiaryName = beneficiaryName;
  }

  public void setBeneficiaryName(@javax.annotation.Nullable String beneficiaryName) {
    this.beneficiaryName = JsonNullable.<String>of(beneficiaryName);
  }

  public StatementPayoutRefund endToEndId(@javax.annotation.Nullable String endToEndId) {
    this.endToEndId = JsonNullable.<String>of(endToEndId);
    
    return this;
  }

  /**
   * Get endToEndId
   * @return endToEndId
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getEndToEndId() {
        return endToEndId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_END_TO_END_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEndToEndId_JsonNullable() {
    return endToEndId;
  }
  
  @JsonProperty(JSON_PROPERTY_END_TO_END_ID)
  public void setEndToEndId_JsonNullable(JsonNullable<String> endToEndId) {
    this.endToEndId = endToEndId;
  }

  public void setEndToEndId(@javax.annotation.Nullable String endToEndId) {
    this.endToEndId = JsonNullable.<String>of(endToEndId);
  }

  public StatementPayoutRefund reasonCode(@javax.annotation.Nullable String reasonCode) {
    this.reasonCode = JsonNullable.<String>of(reasonCode);
    
    return this;
  }

  /**
   * Get reasonCode
   * @return reasonCode
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getReasonCode() {
        return reasonCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REASON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReasonCode_JsonNullable() {
    return reasonCode;
  }
  
  @JsonProperty(JSON_PROPERTY_REASON_CODE)
  public void setReasonCode_JsonNullable(JsonNullable<String> reasonCode) {
    this.reasonCode = reasonCode;
  }

  public void setReasonCode(@javax.annotation.Nullable String reasonCode) {
    this.reasonCode = JsonNullable.<String>of(reasonCode);
  }

  public StatementPayoutRefund reasonDescription(@javax.annotation.Nullable String reasonDescription) {
    this.reasonDescription = JsonNullable.<String>of(reasonDescription);
    
    return this;
  }

  /**
   * Get reasonDescription
   * @return reasonDescription
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getReasonDescription() {
        return reasonDescription.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REASON_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReasonDescription_JsonNullable() {
    return reasonDescription;
  }
  
  @JsonProperty(JSON_PROPERTY_REASON_DESCRIPTION)
  public void setReasonDescription_JsonNullable(JsonNullable<String> reasonDescription) {
    this.reasonDescription = reasonDescription;
  }

  public void setReasonDescription(@javax.annotation.Nullable String reasonDescription) {
    this.reasonDescription = JsonNullable.<String>of(reasonDescription);
  }

  public StatementPayoutRefund uniqueMandateReference(@javax.annotation.Nullable String uniqueMandateReference) {
    this.uniqueMandateReference = JsonNullable.<String>of(uniqueMandateReference);
    
    return this;
  }

  /**
   * The unique reference that unambiguiously identify a mandate signed between the user and the beneficiary. See the [Unique Mandate Reference (UMR)](/guide/overview/glossary.html#unique-mandate-reference-umr) article for more information.
   * @return uniqueMandateReference
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getUniqueMandateReference() {
        return uniqueMandateReference.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_UNIQUE_MANDATE_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUniqueMandateReference_JsonNullable() {
    return uniqueMandateReference;
  }
  
  @JsonProperty(JSON_PROPERTY_UNIQUE_MANDATE_REFERENCE)
  public void setUniqueMandateReference_JsonNullable(JsonNullable<String> uniqueMandateReference) {
    this.uniqueMandateReference = uniqueMandateReference;
  }

  public void setUniqueMandateReference(@javax.annotation.Nullable String uniqueMandateReference) {
    this.uniqueMandateReference = JsonNullable.<String>of(uniqueMandateReference);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatementPayoutRefund statementPayoutRefund = (StatementPayoutRefund) o;
    return Objects.equals(this.payoutRefundId, statementPayoutRefund.payoutRefundId) &&
        Objects.equals(this.payoutId, statementPayoutRefund.payoutId) &&
        equalsNullable(this.payoutTag, statementPayoutRefund.payoutTag) &&
        equalsNullable(this.label, statementPayoutRefund.label) &&
        Objects.equals(this.beneficiaryId, statementPayoutRefund.beneficiaryId) &&
        equalsNullable(this.beneficiaryName, statementPayoutRefund.beneficiaryName) &&
        equalsNullable(this.endToEndId, statementPayoutRefund.endToEndId) &&
        equalsNullable(this.reasonCode, statementPayoutRefund.reasonCode) &&
        equalsNullable(this.reasonDescription, statementPayoutRefund.reasonDescription) &&
        equalsNullable(this.uniqueMandateReference, statementPayoutRefund.uniqueMandateReference);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(payoutRefundId, payoutId, hashCodeNullable(payoutTag), hashCodeNullable(label), beneficiaryId, hashCodeNullable(beneficiaryName), hashCodeNullable(endToEndId), hashCodeNullable(reasonCode), hashCodeNullable(reasonDescription), hashCodeNullable(uniqueMandateReference));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatementPayoutRefund {\n");
    sb.append("    payoutRefundId: ").append(toIndentedString(payoutRefundId)).append("\n");
    sb.append("    payoutId: ").append(toIndentedString(payoutId)).append("\n");
    sb.append("    payoutTag: ").append(toIndentedString(payoutTag)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    beneficiaryId: ").append(toIndentedString(beneficiaryId)).append("\n");
    sb.append("    beneficiaryName: ").append(toIndentedString(beneficiaryName)).append("\n");
    sb.append("    endToEndId: ").append(toIndentedString(endToEndId)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("    reasonDescription: ").append(toIndentedString(reasonDescription)).append("\n");
    sb.append("    uniqueMandateReference: ").append(toIndentedString(uniqueMandateReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

