/*
 * Treezor API
 * As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.  You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.  Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect). 
 *
 * The version of the OpenAPI document: 25.04.03
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sdk.treezor.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TaxResidenceObjectTaxResidencesInner
 */
@JsonPropertyOrder({
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_ID,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_USER_ID,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_COUNTRY,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_TAX_PAYER_ID,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_LIABILITY_WAIVER,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_CREATED_DATE,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_LAST_UPDATE,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_DELETED_DATE,
  TaxResidenceObjectTaxResidencesInner.JSON_PROPERTY_IS_DELETED
})
@JsonTypeName("TaxResidenceObject_taxResidences_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-14T09:49:28.273669400+02:00[Europe/Paris]", comments = "Generator version: 7.12.0")
public class TaxResidenceObjectTaxResidencesInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nullable
  private Integer userId;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_TAX_PAYER_ID = "taxPayerId";
  @javax.annotation.Nullable
  private String taxPayerId;

  public static final String JSON_PROPERTY_LIABILITY_WAIVER = "liabilityWaiver";
  @javax.annotation.Nullable
  private Boolean liabilityWaiver;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  @javax.annotation.Nullable
  private String createdDate;

  public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
  @javax.annotation.Nullable
  private String lastUpdate;

  public static final String JSON_PROPERTY_DELETED_DATE = "deletedDate";
  @javax.annotation.Nullable
  private String deletedDate;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @javax.annotation.Nullable
  private Boolean isDeleted;

  public TaxResidenceObjectTaxResidencesInner() {
  }

  public TaxResidenceObjectTaxResidencesInner id(@javax.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the Tax Residence.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }

  public TaxResidenceObjectTaxResidencesInner userId(@javax.annotation.Nullable Integer userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * The unique identifier of the User.
   * @return userId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@javax.annotation.Nullable Integer userId) {
    this.userId = userId;
  }

  public TaxResidenceObjectTaxResidencesInner country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * The country code for the country of Tax Residence.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public TaxResidenceObjectTaxResidencesInner taxPayerId(@javax.annotation.Nullable String taxPayerId) {
    
    this.taxPayerId = taxPayerId;
    return this;
  }

  /**
   * The Tax Identification Number (TIN) or Tax Code of the User. 
   * @return taxPayerId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_PAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxPayerId() {
    return taxPayerId;
  }


  @JsonProperty(JSON_PROPERTY_TAX_PAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxPayerId(@javax.annotation.Nullable String taxPayerId) {
    this.taxPayerId = taxPayerId;
  }

  public TaxResidenceObjectTaxResidencesInner liabilityWaiver(@javax.annotation.Nullable Boolean liabilityWaiver) {
    
    this.liabilityWaiver = liabilityWaiver;
    return this;
  }

  /**
   * The waiver exempting Treezor from liability in case of a missing TIN.
   * @return liabilityWaiver
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIABILITY_WAIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLiabilityWaiver() {
    return liabilityWaiver;
  }


  @JsonProperty(JSON_PROPERTY_LIABILITY_WAIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiabilityWaiver(@javax.annotation.Nullable Boolean liabilityWaiver) {
    this.liabilityWaiver = liabilityWaiver;
  }

  public TaxResidenceObjectTaxResidencesInner createdDate(@javax.annotation.Nullable String createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

  /**
   * The date of creation of the Tax Residence object.
   * @return createdDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedDate() {
    return createdDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDate(@javax.annotation.Nullable String createdDate) {
    this.createdDate = createdDate;
  }

  public TaxResidenceObjectTaxResidencesInner lastUpdate(@javax.annotation.Nullable String lastUpdate) {
    
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * The date and time at which the Tax Residence has been updated.
   * @return lastUpdate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastUpdate() {
    return lastUpdate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdate(@javax.annotation.Nullable String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public TaxResidenceObjectTaxResidencesInner deletedDate(@javax.annotation.Nullable String deletedDate) {
    
    this.deletedDate = deletedDate;
    return this;
  }

  /**
   * The date and time at which the Tax Residence has been deleted.
   * @return deletedDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeletedDate() {
    return deletedDate;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedDate(@javax.annotation.Nullable String deletedDate) {
    this.deletedDate = deletedDate;
  }

  public TaxResidenceObjectTaxResidencesInner isDeleted(@javax.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Whether or not the Tax Residence object was deleted.
   * @return isDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@javax.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxResidenceObjectTaxResidencesInner taxResidenceObjectTaxResidencesInner = (TaxResidenceObjectTaxResidencesInner) o;
    return Objects.equals(this.id, taxResidenceObjectTaxResidencesInner.id) &&
        Objects.equals(this.userId, taxResidenceObjectTaxResidencesInner.userId) &&
        Objects.equals(this.country, taxResidenceObjectTaxResidencesInner.country) &&
        Objects.equals(this.taxPayerId, taxResidenceObjectTaxResidencesInner.taxPayerId) &&
        Objects.equals(this.liabilityWaiver, taxResidenceObjectTaxResidencesInner.liabilityWaiver) &&
        Objects.equals(this.createdDate, taxResidenceObjectTaxResidencesInner.createdDate) &&
        Objects.equals(this.lastUpdate, taxResidenceObjectTaxResidencesInner.lastUpdate) &&
        Objects.equals(this.deletedDate, taxResidenceObjectTaxResidencesInner.deletedDate) &&
        Objects.equals(this.isDeleted, taxResidenceObjectTaxResidencesInner.isDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, country, taxPayerId, liabilityWaiver, createdDate, lastUpdate, deletedDate, isDeleted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxResidenceObjectTaxResidencesInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    taxPayerId: ").append(toIndentedString(taxPayerId)).append("\n");
    sb.append("    liabilityWaiver: ").append(toIndentedString(liabilityWaiver)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    deletedDate: ").append(toIndentedString(deletedDate)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

