openapi: 3.0.1
info:
  contact:
    name: Treezor
    url: https://treezor.com
  description: |
    As a REST API, Treezor accepts and returns JSON payloads, along with the associated `application/json` content type.

    You can learn everything you need to know about authentication, credentials, data formats, and more in the [API Basics](/guide/api-basics/environments.html) section.

    Like the rest of the documentation, this reference focuses on the latest version of the Treezor API (Connect).
  title: Treezor API
  version: 25.04.03
servers:
- url: https://baseURL.co
- description: Sandbox environment
  url: https://your-company-name.sandbox.treezor.co
- description: Production environment
  url: https://your-company-name.api.treezor.com
tags:
- description: |
    The Account Details object corresponds to the bank details of the Wallet, with all the relevant information such as the IBAN and the owner's identity.

    _Related articles: [Account Details](/guide/wallets/account-details.html) | [Wallets](/guide/wallets/introduction.html)_
  name: Account Details
- description: "The Account Statement object synthesizes all operations affecting\
    \ the [Balance](/guide/overview/glossary#balance) of a [Wallet](/guide/wallets/introduction.html)\
    \ for a given month. It also provides the Balance at the start and end of that\
    \ month, the sum of debits, and the sum of credits. \n\n_Related articles: [Account\
    \ Statements](/guide/wallets/account-statements.html) | [Wallets](/guide/wallets/introduction.html)_\n"
  name: Account Statements
- description: "Card Acquiring consists of capturing funds from a third-party card\
    \ to credit a Treezor [Wallet](/guide/wallets/introduction.html). \n\n_Related\
    \ articles: [Card Acquiring](/guide/acquiring/introduction.html)_\n"
  name: Acquiring (Card Topups)
- description: |
    Dedicated set of endpoints so emulate card acquiring payins, and the related notifications.

    _Related articles: [Card Acquiring](/guide/acquiring/introduction.html) | [Emulation](/guide/acquiring/faking-operations.html)_
  name: Acquiring (Simulation)
- description: |
    Treezor offers a series of templates to customize emails and files, that you can manage via dedicated endpoints. Please bear in mind templates are base64-encoded files.

    _Related articles: [Templates](/guide/api-basics/templates.html) | [Email Templates](/guide/api-basics/emails.html#templates)_
  name: API Templates
- description: |
    Treezor leverages the [OAuth2 framework](https://en.wikipedia.org/wiki/OAuth) and [JSON Web Token (JWT)](/guide/overview/glossary.html#json-web-token-jwt) which allows for a wide range of authentication flows.

    The obtained Bearer access token can then be used in the Authorization headers to authenticate your calls to the Treezor API.

    _Related articles: [Authentication](/guide/api-basics/authentication.html)_
  name: Authentication
- description: |
    The Balance object provides the amount available on a given Wallet. Read more about the different kind of balances in the [Balance definition](/guide/overview/glossary.html#balance) of the Glossary.

    _Related articles: [Balances](/guide/wallets/balances.html) | [Wallets](/guide/wallets/introduction.html)_
  name: Balances
- description: "The Beneficiary object represents a bank account that is outside of\
    \ your Treezor ecosystem (as opposed to [Wallets](/guide/dashboard/wallets.html#wallets)).\
    \ \n\nThey are therefore the target of payouts (SEPA Direct Debit and SEPA Credit\
    \ Transfers), and are necessarily attached to a User.\n\n_Related articles: [Beneficiaries](/guide/transfers/beneficiaries.html)\
    \ | [SEPA Transfers](/guide/transfers/introduction.html)_\n"
  name: Beneficiaries
- description: |
    Treezor provides dedicated endpoints to help you check information regarding a legal entity, provided you have its VAT or registration number.

    _Related articles: [Checking for veracity](/guide/users/legal-entity.html#checking-for-veracity) | [Legal Entities](/guide/users/legal-entity.html)_
  name: Businesses
- description: |
    The Card object represents a Physical or Virtual Card issued with Treezor services.

    Following your [Card Program](/guide/cards/introduction.html#card-program) and your agreement with Treezor, you can issue, manage, and configure cards with options, restrictions, and limits to best suit your use case.

    _Related articles: [Cards](/guide/cards/introduction.html) | [Creation](/guide/cards/creation.html) | [Modifications](/guide/cards/modification.html) | [Restrictions & limits](/guide/cards/restrictions-limits.html)_
  name: Cards
- description: |
    Treezor allows you to create cards in bulk with a dedicated set of endpoints.

    _Related articles: [Bulk Creation](/guide/cards/creation.html#bulk-creation) | [Cards](/guide/cards/introduction.html)_
  name: Cards Bulk Creation
- description: |
    **Deprecated** – See [Digitized Cards](/api-reference/api-endpoints.html#tag/Digitized%20Cards/tavRequestPOST) instead.
  name: Cards Digitalization
- description: "When eligible to SCA, most card transactions must be authenticated,\
    \ hence ensuring the legitimate cardholder is initiating the transaction. \n\n\
    For the authentication step to be SCA-compliant, you must enroll the card for\
    \ out of band authentication.\n\n_Related articles: [Card enrollment](/guide/strong-customer-authentication/securing-endpoints.html#sca-for-card-transactions)\
    \ | [SCA](/guide/strong-customer-authentication/introduction.html)_\n"
  name: Card 3DSecure Enrollment (SCA)
- description: |
    The Ruleset object of the Multi-Criteria Dynamic Card rules engine allows you to authorize or refuse a Card Transaction based on your own set of rules.

    _Related articles: [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html)_
  name: Card Rulesets (MDC)
- description: |
    The Card Transaction object represents a step of a card payment made with a Treezor-issued Card (e.g., authorization, settlement, or refund).

    Card Transactions relating to the same payment (or payment attempt) have the same `paymentId` value.

    _Related articles: [Card Transactions](/guide/cards/transactions.html) | [Transactions life cycle](/guide/cards/transactions-lifecycle.html) | [Transaction examples](/guide/cards/transactions-examples.html)_
  name: Card Transactions
- description: |
    The Country Restriction Group object is a whitelist or blacklist of countries. These lists allow you to specify if a given card should be used in specific countries (or forbidden in some countries).

    _Related articles: [List-based restrictions](/guide/cards/restrictions-limits.html#country-restrictions) | [Cards](/guide/cards/introduction.html)_
  name: Country Restriction Groups
- description: |
    The digitization of a Card is the act of tokenizing an existing Card and store it in a Google Pay, Apple Pay, or Samsung Pay wallet.

    _Related articles: [X-Pay](/guide/cards/x-pay-google-apple.html) | [Cards](/guide/cards/introduction.html)_
  name: Digitized Cards
- description: "The Mandate object represents the formal document allowing a [Legal\
    \ Entity](/guide/users/legal-entity.html) to initiate a transfer of funds from\
    \ somebody else's account, to theirs. \n\nThe transfer is made using [SEPA Direct\
    \ Debit (SDDE)](direct-debit#emitted-direct-debits-sdde) and can be used to receive\
    \ one-time or recurring payments.\n\n_Related articles: [Mandates](/guide/transfers/mandates.html)\
    \ | [SEPA Direct Debit](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde)_\n"
  name: Mandates
- description: |
    The MCC List of the Multi-Criteria Dynamic Card rules engine allows you to predefine and manage lists of [Merchant Category Codes (MDCC)](/guide/overview/glossary.html#merchant-category-code-mcc) that you can then add to your Rulesets.

    _Related articles: [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html)_
  name: MCC Lists (MDC)
- description: |
    The MMC Restriction Group object represents a list-based restriction allowing you to limit the usage of the card to specific categories of merchants.

    _Related articles: [List-based restrictions](/guide/cards/restrictions-limits.html#mcc-restrictions) | [Cards](/guide/cards/introduction.html)_
  name: MCC Restriction Groups
- description: |
    The MID Restriction Group object is a list-based restriction allowing you to limit the usage of the card to specific merchants.

    _Related articles: [List-based restrictions](/guide/cards/modification.html#list-based-restrictions) | [Cards](/guide/cards/introduction.html)_
  name: Merchant ID Restriction Groups
- description: "In some cases, the [Merchant Id (MID)](/guide/overview/glossary.html#merchant-identification-number-mid)\
    \ may not be up-to-date or the given information not enough for you to act on\
    \ it. \n\nTreezor offers endpoints to add metadata to MIDs, hence allowing you\
    \ to add human-readable information as you see fit.\n\n_Related articles: [MID\
    \ Metadata](/guide/cards/restrictions-limits.html#mid-restrictions) | [Cards](/guide/cards/introduction.html)_\n"
  name: Merchant ID Metadata
- description: |
    The MID List of the Multi-Criteria Dynamic Card rules engine allows you to predefine and manage lists of [Merchant IDs (MID)](/guide/overview/glossary.html#merchant-identification-number-mid) that you can then add to your Rulesets.

    _Related articles: [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html)_
  name: MID Lists (MDC)
- description: "The Operation object represents for banking operations originating\
    \ from or targeting a [Wallet](/guide/wallets/introduction.html) (i.e., Card Transactions,\
    \ Payins, Payouts, and Transfers) and their refunds. \n\nEach Operation summarizes\
    \ the initial transaction with read-only information such as the nature, status,\
    \ amount, origin, and destination.\n\n_Related articles: [Operations](/guide/operations/introduction.html)_\n"
  name: Operations
- description: |
    The Payin object represents a movement of fund from an external account to a Treezor Wallet, and thus regardless of the means of payment used (SEPA Transfers, Checks, Card Top-ups).

    _Related articles: [SCTR](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr) | [SDDE](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde) | [Card top-up](/guide/acquiring/introduction.html) | [Check](/guide/cheques/introduction.html)_
  name: Payins
- description: |
    The Payin Refund object represents the reimbursement of a Payin.

    Related articles: [SCTR Recalls](/guide/transfers/sepa-recalls.html#receiving-sctr-recalls)
  name: Payin Refunds
- description: |
    The Payout object represents a movement of funds from a Treezor Wallet to an external account, specifically the ones made through SEPA Transfers.

    _Related articles: [Card Transactions](/guide/cards/transactions.html) | [SCTE](/guide/transfers/credit-transfer.html#emitted-credit-transfers-scte) | [SDDR](/guide/transfers/direct-debit.html#received-direct-debits-sddr)_
  name: Payouts
- description: "The Payout Refund object represents the reimbursement of a Payout.\
    \ \n\n_Related articles: [SCTE Inst Recalls](/guide/transfers/sepa-recalls.html#emitting-scte-inst-recalls)_\n"
  name: Payout Refunds
- description: |
    Recalls occur when the originator of a [SEPA Credit Transfer (SCT)](/guide/overview/glossary.html#sepa-credit-transfer-sct) ask to reverse the transfer.

    Treezor offers endpoints to generate these requests or answers them depending on the type of the initial transfer.

    _Related articles: [Recalls & RROs](/guide/transfers/sepa-recalls.html)_
  name: Recalls
- description: "Scheduled Payment orders allow you to plan a payment execution in\
    \ the future, whether it is a unique operation or recurring ones. \n\nScheduled\
    \ Payments can be used for both [Payouts (SCTE)](/guide/transfers/credit-transfer.html#emitted-credit-transfers-scte)\
    \ and [Wallet-to-Wallet Transfers](/guide/wallets/wallet-to-wallet.html#wallet-to-wallet-transfers).\n\
    \n_Related articles: [Scheduled Payments](/guide/transfers/scheduled-payments.html)\
    \ | [SCTE](/guide/transfers/credit-transfer.html#emitted-credit-transfers-scte)\
    \ | [Wallet-to-Wallet](/guide/transfers/wallet-to-wallet.html)_\n"
  name: Scheduled Payments
- description: |
    The SCA Wallet object represents the secure enclave locally present on a device, which contains the private key for Strong Customer Authentication.

    _Related articles: [SCA Wallets](/guide/strong-customer-authentication/introduction.html#sca-wallet-object) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  name: SCA
- description: |
    The External Operation object represents any end user sensitive action that you need to declare when eligible to Strong Customer Authentication.

    When applying SCA outside of Treezor services, you're legally required to declare these actions to Treezor. Treezor then uses these declarations for reporting to the regulator.

    _Related articles: [SCA External Operations](/guide/strong-customer-authentication/securing-endpoints.html#declaring-sca-external-operations) | [SCA](/guide/strong-customer-authentication/introduction.html)_
  name: SCA External Operations
- description: "You can generate fake SCA proofs in Sandbox for testing your strong\
    \ customer authentication integration. \n\n_Related articles: [SCA Proof Simulation](/guide/strong-customer-authentication/faking-operations.html#simulate-sca-proof)\
    \ | [SCA](/guide/strong-customer-authentication/introduction.html)_\n"
  name: SCA Proof Simulation
- description: |
    Support Users represent your employees, with specific access to your back office and/or the [Dashboard](/guide/dashboard/introduction.html) to manage your end users.

    Contrary to end users, Support Users don't have [Wallets](/guide/wallets/introduction.html), [Cards](/guide/cards/introduction.html), and cannot initiate of funds related operations.

    _Related articles: [Support Users](/guide/users/support.html) | [Dashboard Users](/guide/dashboard/dashboard-users.html)_
  name: Support Users
- description: |
    Transactions are a read-only representation of banking operations on a [Wallet](./introduction).

    If you are using [Treezor Connect](/guide/overview/getting-started.html#treezor-api), the [Operations](/guide/operations/introduction.html) endpoint supersedes this one.

    _Related articles: [Transactions](/guide/wallets/transactions.html) | [Wallets](/guide/wallets/introduction.html)_
  name: Transactions
- description: |
    The Transfer object represents a movement of funds from one Treezor Wallet to another.

    Both Wallets must belong to the same Treezor environment in order to perform a Wallet-to-Wallet Transfer (also referred to as peer-to-peer or P2P).

    _Related articles: [Wallet-to-Wallet](/guide/transfers/wallet-to-wallet.html) | [Wallets](/guide/wallets/introduction.html)_
  name: Transfers
- description: "Dedicated set of endpoints for uploading documents to Treezor with\
    \ a built-in pre-validation process.\n\n* Users upload files through pre-signed\
    \ forms. \n* These files are stored on dedicated servers while your teams review\
    \ them. \n* The actual Document objects are created in the Treezor API once the\
    \ files are validated.\n\n_Related articles: [Document Pre-review](/guide/user-verification/documents-prereview.html)\
    \ | [User verification](/guide/user-verification/introduction.html)_\n"
  name: User Document Pre-review
- description: "Documents are evidence required by Treezor to ensure Users are who\
    \ they claim to be.\n\nDuring the KYC/B review, Treezor compares documents to\
    \ the user’s declarative data. \nThe user is verified if the documents are in\
    \ order (as well as any other verification requirement).\n\n_Related articles:\
    \ [Documents](/guide/user-verification/documents.html) | [User verification](/guide/user-verification/introduction.html)_\n"
  name: User Documents
- description: |
    Treezor is legally obligated to verify the identity of the users using its services, whether it's you as a company or your end users.

    Once you've provided all the relevant information regarding a user, you may request the KYC Review, so that Treezor's team can either validate or refuse the user.

    _Related articles: [KYC Request](/guide/user-verification/kyc-request.html) | [User verification](/guide/user-verification/introduction.html)_
  name: User KYC Review
- description: "All users (both physical users and legal entities) going through the\
    \ KYC verification process must declare at least one country of tax residency.\
    \ \n\nThis is an obligation enforced by the [CRS](/guide/overview/glossary.html#common-reporting-standard-crs)\
    \ and [FATCA](/guide/overview/glossary.html#foreign-account-tax-compliance-act-fatca).\n\
    \n_Related articles: [Tax residence](/guide/user-verification/tax-residence.html)\
    \ | [User verification](/guide/user-verification/introduction.html)_\n"
  name: User Tax Residences
- description: |
    The User object usually represents your customers, also referred to as end users. They can either be physical users or legal entities.

    _Related articles: [Physical Users](/guide/users/physical.html) | [Legal Entities](/guide/users/legal-entity.html) | [Users](https://docs.treezor.com/guide/users/introduction.html)_
  name: Users
- description: "Treezor relies on several verification solutions to ease the physical\
    \ user verification process. \n\nThe solutions available to you depend on the\
    \ type of user and the distribution country.\n\n_Related articles: [User verification](/guide/user-verification/introduction.html)_\n"
  name: Verification Solutions (KYC)
- description: |
    In addition to the automatically assigned IBAN, Virtual IBANs can be created. Wallets can have as many Virtual IBANs as you see fit, to answer a large variety of use cases.

    _Related articles: [IBAN](/guide/wallets/iban.html) | [Wallets](/guide/wallets/introduction.html)_
  name: Virtual IBANs
- description: "The Wallet object is like an account holding funds. They are necessary\
    \ for any type of transaction in the Treezor environment.\n\nWallets are usually\
    \  attached to your end users, allowing for the setup of their means of payment\
    \ (cards, transfers, etc.). \nTreezor offers various types of wallets to adapt\
    \ to multiple use cases and technical architectures while remaining compliant\
    \ in a highly regulated context.\n\n_Related articles: [Wallets](/guide/wallets/introduction.html)_\n"
  name: Wallets
paths:
  /core-connect/account-details/{walletId}/raw:
    get:
      description: |
        Retrieve the necessary data (JSON) to generate the Account Details of a given Wallet.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getRawWalletAccountDetail
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get JSON Account Details
      tags:
      - Account Details
      x-accepts:
      - application/json
  /core-connect/account-details/{walletId}/computed:
    get:
      description: |
        Retrieve a Wallet RIB and IBAN in PDF format.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getComputedWalletAccountDetail
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get PDF Account Details
      tags:
      - Account Details
      x-accepts:
      - application/json
  /oauth/token:
    post:
      description: |
        Exchange authorization codes or refresh tokens for access tokens.
        The response will include the access token and optionally a refresh token, along with their expiration details.
      operationId: postAuth
      security: []
      summary: Obtain Access Token
      tags:
      - Authentication
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /core-connect/balances/{walletId}:
    get:
      description: Retrieve the Balance History of a Wallet.
      operationId: getWalletBalanceHistory
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Wallet Balance history
      tags:
      - Balances
      x-accepts:
      - application/json
  /core-connect/cardtransactions:
    get:
      description: Retrieve all the Card Transactions. This is the preferred request
        for a dashboard-oriented approach. You shouldn't expose this endpoint to your
        end users.
      operationId: getCoCardTransactions
      security:
      - OAuth2:
        - read_only
        - admin
      summary: Get all Card Transactions
      tags:
      - Card Transactions
      x-accepts:
      - application/json
  /core-connect/cardtransactions/{cardId}:
    get:
      description: Retrieve the Card Transactions for a specific card. This request
        is preferred for a dashboard-oriented usage. You shouldn't expose this endpoint
        to your end users.
      operationId: getCoCardTransaction
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Card Transactions
      tags:
      - Card Transactions
      x-accepts:
      - application/json
  /core-connect/support-user:
    get:
      description: Retrieve all the Support Users.
      operationId: getAllSupportUser
      security:
      - OAuth2:
        - support_user_management
      summary: Get all Support Users
      tags:
      - Support Users
      x-accepts:
      - application/json
    post:
      description: Create a new Support User.
      operationId: createSupportUser
      security:
      - OAuth2:
        - support_user_management
      summary: Create Support User
      tags:
      - Support Users
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/support-user/{supportUserId}:
    delete:
      description: Delete a Support User
      operationId: deleteSupportUser
      security:
      - OAuth2:
        - support_user_management
      summary: Delete Support User
      tags:
      - Support Users
      x-accepts:
      - application/json
    get:
      description: Retrieve a Support User based on its `id`.
      operationId: findOneSupportUserById
      security:
      - OAuth2:
        - support_user_management
        - read_only
      summary: Get Support User
      tags:
      - Support Users
      x-accepts:
      - application/json
    put:
      description: Modify a Support User information.
      operationId: updateSupportUser
      security:
      - OAuth2:
        - support_user_management
      summary: Update Support User
      tags:
      - Support Users
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/support-user/{supportUserId}/unblock:
    put:
      description: Unblock a Support User. Support Users may be blocked if they failed
        to login 3 times in a row.
      operationId: unblockSupportUser
      security:
      - OAuth2:
        - support_user_management
      summary: Unblock Support User
      tags:
      - Support Users
      x-accepts:
      - application/json
  /core-connect/mid/metadata:
    get:
      description: Retrieve all MID metadata.
      operationId: getAllMidMetadata
      security:
      - OAuth2:
        - admin
      summary: Get all MID metadata
      tags:
      - Merchant ID Metadata
      x-accepts:
      - application/json
    put:
      description: Create or update bulk metadata
      operationId: putMidMetadata
      security:
      - OAuth2:
        - admin
      summary: Put Bulk metadata
      tags:
      - Merchant ID Metadata
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/mid/{mid}/metadata:
    get:
      description: Retrieve metadata for a Merchant Id.
      operationId: getMidMetadata
      security:
      - OAuth2:
        - admin
      summary: Get MID Metadata
      tags:
      - Merchant ID Metadata
      x-accepts:
      - application/json
    put:
      description: Store metadata for a Merchant Id.
      operationId: postMidMetadata
      security:
      - OAuth2:
        - admin
      summary: Store MID Metadata
      tags:
      - Merchant ID Metadata
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/payouts/{payoutId}/proof:
    get:
      description: |
        Generate and download a proof of payout in .PDF format. See [Proof of Payout](/guide/transfers/proof-of-payout.html) for more information.
      operationId: getProofPayout
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Create Payout Proof
      tags:
      - Payouts
      x-accepts:
      - application/json
  /core-connect/card/bulk/{id}/report:
    get:
      description: |
        Get a link to download the bulk card creation report.

        The link expires after 5 minutes.
      operationId: getCardBulkReport
      security:
      - OAuth2:
        - admin
      summary: Get Report
      tags:
      - Cards Bulk Creation
      x-accepts:
      - application/json
  /core-connect/card/bulk:
    get:
      description: Search bulk card orders.
      operationId: getBulkCard
      security:
      - OAuth2:
        - admin
      summary: Get Bulk Card Order
      tags:
      - Cards Bulk Creation
      x-accepts:
      - application/json
    post:
      description: |
        Create a Bulk Card order to create multiple cards at once.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postBulkCard
      security:
      - OAuth2:
        - admin
      summary: Create Bulk Card Order
      tags:
      - Cards Bulk Creation
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/operations/{walletId}/report:
    get:
      description: Retrieve an Operations Report based on the corresponding Wallet
        `id`.
      operationId: getOperationsReport
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Operations Report
      tags:
      - Operations
      x-accepts:
      - application/json
    post:
      description: Create a CSV export that includes all operations for a given Wallet
        on a given period.
      operationId: postOperationsReport
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Create Operations Report
      tags:
      - Operations
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/merchantIdRestrictionGroups/{groupId}/mid/metadata:
    get:
      description: Retrieve all Merchant Ids with metadata.
      operationId: getAllMidMetadataBYyGroup
      security:
      - OAuth2:
        - read_write
      summary: Get all MID with metadata
      tags:
      - Merchant ID Metadata
      x-accepts:
      - application/json
  /customization/templates:
    get:
      description: Retrieve the list of templates.
      operationId: getTemplates
      security:
      - OAuth2:
        - admin
      summary: Get Available Templates
      tags:
      - API Templates
      x-accepts:
      - application/json
  /customization/templates/{templateName}:
    delete:
      description: Delete a Template.
      operationId: deleteTemplate
      security:
      - OAuth2:
        - admin
      summary: Delete Template
      tags:
      - API Templates
      x-accepts:
      - application/json
    get:
      description: Retrieve the list of variables for the given template
      operationId: getTemplateVariables
      security:
      - OAuth2:
        - admin
      summary: Get Template Variables
      tags:
      - API Templates
      x-accepts:
      - application/json
  /customization/templates/{templateName}/template:
    get:
      description: Retrieve the currently configured template.
      operationId: getTemplate
      security:
      - OAuth2:
        - admin
      summary: Get Template
      tags:
      - API Templates
      x-accepts:
      - application/json
    put:
      description: Upload a replacement for an existing Template.
      operationId: putTemplateUpload
      security:
      - OAuth2:
        - admin
      summary: Upload Template
      tags:
      - API Templates
      x-content-type: application/json
      x-accepts:
      - application/json
  /customization/templates/{templateName}/example:
    get:
      description: Test your template by building one with dummy values.
      operationId: getTemplateExample
      security:
      - OAuth2:
        - admin
      summary: Build Template Example
      tags:
      - API Templates
      x-accepts:
      - application/json
  /core-connect/users/{userId}/kyc/document:
    get:
      description: Retrieve all pre-review documents for given user
      operationId: getKYCDocuments
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Pre-review Documents
      tags:
      - User Document Pre-review
      x-accepts:
      - application/json
    post:
      description: Generate a pre-signed form to upload documents for pre-review.
        Expires after 5 minutes.
      operationId: getPreSignedKycForm
      security:
      - OAuth2:
        - read_write
      summary: Create Upload Document Form
      tags:
      - User Document Pre-review
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/kyc/documents/{documentId}/status:
    put:
      description: Update the pre-review status and comment of the document.
      operationId: updateDocument
      security:
      - OAuth2:
        - legal
      summary: Pre-review Document
      tags:
      - User Document Pre-review
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/kyc/documents/{documentId}:
    delete:
      description: Delete a pre-review document.
      operationId: deleteKYCDocumentcument
      security:
      - OAuth2:
        - legal
      summary: Delete Pre-review Document
      tags:
      - User Document Pre-review
      x-accepts:
      - application/json
  /core-connect/kyc/documents/need-review:
    get:
      description: |
        Retrieve all pre-review documents to review. This endpoint is for [Onboarded Users](/api-reference/api-endpoints.html#tag/User%20Onboarding) only.
      operationId: getKYCDocumentsToReview
      security:
      - OAuth2:
        - legal
      summary: Search Documents to pre-review
      tags:
      - User Document Pre-review
      x-accepts:
      - application/json
  /core-connect/kyc/documents/{documentId}/preview:
    get:
      description: Retrieve the pre-signed URL to download the pre-review document.
      operationId: getPresignedUrlDocument
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Download URL
      tags:
      - User Document Pre-review
      x-accepts:
      - application/json
  /core-connect/operations:
    get:
      description: |
        Retrieve Operations that match your search conditions. The request must specify at least: `walletId`, `dateTo`, `dateFrom`.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html) for operations that are more than 90 days old.
      operationId: getOperations
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Operations
      tags:
      - Operations
      x-accepts:
      - application/json
  /core-connect/sca/scawallets:
    get:
      description: "Retrieve the list of [SCA Wallets](/guide/strong-customer-authentication/introduction.html#sca-wallet-object)\
        \ for a given user."
      operationId: getSCAWallets
      security:
      - OAuth2:
        - read_only
      summary: Search SCA Wallets
      tags:
      - SCA
      x-accepts:
      - application/json
    post:
      description: "Create a new [SCA Wallet](/guide/strong-customer-authentication/introduction.html#sca-wallet-object)\
        \ manually."
      operationId: postScaWallet
      security:
      - OAuth2:
        - read_write
      summary: Create SCA Wallet
      tags:
      - SCA
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/sca/scawallets/swap:
    post:
      description: Create an SCA Wallet while deleting the previous one as users should
        have only one device enrolled.
      operationId: swapSCAWallets
      security:
      - OAuth2:
        - read_write
      summary: Swap SCA Wallets
      tags:
      - SCA
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/sca/scawallets/{scaWalletId}:
    delete:
      description: Permanently delete an SCA Wallet.
      operationId: deleteScaWallet
      security:
      - OAuth2:
        - read_write
      summary: Delete SCA Wallet
      tags:
      - SCA
      x-accepts:
      - application/json
    get:
      description: Retrieve an SCA Wallet by providing its `id`.
      operationId: getScaWallet
      security:
      - OAuth2:
        - read_only
      summary: Get SCA Wallet
      tags:
      - SCA
      x-accepts:
      - application/json
  /core-connect/sca/scawallets/{scaWalletId}/lock:
    put:
      description: |
        Locks an SCA Wallet so that none of the services it offers can be unlocked until it is unlocked.
      operationId: putScaWallet
      security:
      - OAuth2:
        - read_write
      summary: Lock SCA Wallet
      tags:
      - SCA
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/sca/scawallets/{scaWalletId}/unlock:
    put:
      description: Unlock an SCA Wallet.
      operationId: unlockScaWallet
      security:
      - OAuth2:
        - read_write
      summary: Unlock SCA Wallet
      tags:
      - SCA
      x-accepts:
      - application/json
  /core-connect/sca/scawallets/{scaWalletId}/resetPin:
    put:
      description: |
        Reset the PIN code of an SCA Wallet if the user has locked their Wallet after too many consecutive wrong PIN attempts. See [Reset PIN (Mobile)](/guide/strong-customer-authentication/sca-wallet-lifecycle.html#reset-pin-mobile) for more information.

        Once the PIN reset, the Customer can set a new PIN via the mobile application.
      operationId: resetScaWalletPin
      security:
      - OAuth2:
        - legal
      summary: Reset PIN
      tags:
      - SCA
      x-accepts:
      - application/json
  /core-connect/sca/setPasscode:
    put:
      description: |
        Change the passcode ([Web Native SCA](/guide/strong-customer-authentication/introduction.html#web-native)).
      operationId: setPasscode
      security:
      - OAuth2:
        - read_write
      summary: Change Passcode
      tags:
      - SCA
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/scaProof:
    post:
      description: "Create an `scaProof` for testing SCA authentication flows without\
        \ a dedicated frontend. Use the `scaProof` to secure end user flow with a\
        \ `delegated_end_user` JWT in `sandbox`. \n\nSee the [Simulate SCA Proof](/guide/strong-customer-authentication/faking-operations.html#simulate-sca-proof)\
        \ article for more information.\n"
      operationId: postScaProof
      security:
      - OAuth2:
        - admin
      summary: Simulate SCA Proof
      tags:
      - SCA Proof Simulation
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/sca/externalOperations:
    post:
      description: "Declare an SCA External Operation (i.e., a sensitive action that\
        \ was made outside of Treezor services)."
      operationId: postExtOperation
      security:
      - OAuth2:
        - read_write
      summary: Create External Operation declaration
      tags:
      - SCA External Operations
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/sca/externalOperations/{externalOperationId}:
    put:
      description: "Modify an SCA External Operation declaration. \n\nThis feature\
        \ is only available for Per Operation operations, in other words for external\
        \ operations whose action name is: `externalMassPayoutOrderCreation`, \n`externalMassTransferOrderCreation`,\
        \ `externalScheduledPayoutOrder`, or `externalScheduledTransferOrder`.\n"
      operationId: putExtOperation
      security:
      - OAuth2:
        - read_write
      summary: Update External Operation declaration
      tags:
      - SCA External Operations
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/statements/{walletId}/raw:
    get:
      description: |
        Retrieve the raw data (json) to build a Wallet account statement.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getRawStatement
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get JSON Account Statement
      tags:
      - Account Statements
      x-accepts:
      - application/json
  /core-connect/statements/{walletId}/computed:
    get:
      description: |
        Retrieve a Wallet account statement in pdf format.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getPdfAccountStatement
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get PDF Account Statement
      tags:
      - Account Statements
      x-accepts:
      - application/json
  /v1/balances:
    get:
      description: Retrieve Balances for a given `walletId` or `userId`.
      operationId: getBalances
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Balances
      tags:
      - Balances
      x-accepts:
      - application/json
  /v1/beneficiaries:
    get:
      description: Retrieve Beneficiary bank accounts that match search criteria.
      operationId: getBeneficiaries
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Search Beneficiaries
      tags:
      - Beneficiaries
      x-accepts:
      - application/json
    post:
      description: |
        Create a new benefeciary bank account. This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postBeneficiary
      security:
      - OAuth2:
        - read_write
      summary: Create Beneficiary
      tags:
      - Beneficiaries
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/beneficiaries/{beneficiaryId}:
    get:
      description: Retrieve a Beneficiary bank account based on its `id`.
      operationId: getBeneficiary
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Beneficiary
      tags:
      - Beneficiaries
      x-accepts:
      - application/json
    put:
      description: |
        Modify a benefeciary bank account information.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putBeneficiary
      security:
      - OAuth2:
        - read_write
      summary: Update Beneficiary
      tags:
      - Beneficiaries
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/businesssearchs:
    get:
      description: |
        Check information regarding a legal entity.
      operationId: searchBusiness
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Businesses
      tags:
      - Businesses
      x-accepts:
      - '*/*'
      - application/json
  /v1/businessinformations:
    get:
      description: |
        The get business information endpoint returns all already known business information. End user will have then to verify/correct it.
      operationId: getBusinessInfo
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Business Information
      tags:
      - Businesses
      x-accepts:
      - '*/*'
      - application/json
  /v1/cards:
    get:
      description: Retrieve Cards based on search criteria.
      operationId: getCards
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Cards
      tags:
      - Cards
      x-accepts:
      - application/json
  /v1/cards/{cardId}:
    get:
      description: Retrieve a Card based on its `id`.
      operationId: getCard
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Card
      tags:
      - Cards
      x-accepts:
      - application/json
    put:
      description: |
        Update the restriction groups of the card, as well as the `cardTag`.
      operationId: putCard
      security:
      - OAuth2:
        - read_write
      summary: Update Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/CreateVirtual:
    post:
      description: |
        Create a new virtual card. To use a card, it must be activated (`/v1/cards/{cardId}/Activate`).

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postCardVirtual
      security:
      - OAuth2:
        - read_write
      summary: Create Virtual Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/RequestPhysical:
    post:
      description: |
        Create a new physical card. To use a card, it must be activated (`/cards/{id}/Activate`).

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postCardPhysical
      security:
      - OAuth2:
        - read_write
      summary: Create Physical Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/Register3DS:
    post:
      description: |
        Register a card to 3D secure service. The user's mobile number must begin with `+`, or `00`, and the country dialing code.
      operationId: post3ds
      security:
      - OAuth2:
        - read_write
      summary: Register 3D secure
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cardimages:
    get:
      description: |
        Retrieve a virtual card image.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: getCardImage
      security:
      - OAuth2:
        - read_write
      summary: Get Card Image
      tags:
      - Cards
      x-accepts:
      - application/json
  /v1/cards/{cardId}/Activate:
    put:
      description: |
        Activate the Card (updating the `isLive` attribute to `1`). A Card must be activated to be used.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: activateCard
      security:
      - OAuth2:
        - read_write
      summary: Activate Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardToken}/public-token-activation:
    put:
      description: |
        Activate the Card (updating the `isLive` attribute to `1`). Ideal for end user oriented action. A Card must be activated to be used.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: activateCardToken
      security:
      - OAuth2:
        - read_write
      summary: Activate Card Public Token
      tags:
      - Cards
      x-accepts:
      - application/json
  /v1/cards/{cardId}/Assign:
    put:
      description: |
        Assign the Card to another User or Wallet.
      operationId: reassignCard
      security:
      - OAuth2:
        - read_write
      summary: Reassign Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/AssignWallet:
    put:
      description: |
        Assign the Card to another Wallet.
      operationId: assignCardWallet
      security:
      - OAuth2:
        - legal
        - admin
        - read_write
      summary: Assign Wallet
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/ChangePIN:
    put:
      description: |
        Change the Card PIN code knowing the current one.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: changePin
      security:
      - OAuth2:
        - read_write
      summary: Change Card PIN
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/ConvertVirtual:
    put:
      description: |
        Convert a virtual Card into a physical one. The converted card will be both virtual and physical.
      operationId: convertVirtual
      security:
      - OAuth2:
        - read_write
      summary: Convert virtual card to physical
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/Limits:
    put:
      description: |
        Modify the Card limits.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putLimits
      security:
      - OAuth2:
        - read_write
      summary: Update Card Limits
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/LockUnlock:
    put:
      description: |
        Block or unblock a card.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: updateBlockStatus
      security:
      - OAuth2:
        - read_write
      summary: Update Card Lock Status
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/Options:
    put:
      description: |
        Modify the Card permissions group.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: cardOptions
      security:
      - OAuth2:
        - read_write
      summary: Update Card Options
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/Regenerate:
    put:
      description: "Recreate the card image if the card is unlocked. \n\nUseful when\
        \ changing card design, company name, or when retrieving the image results\
        \ in a 404.\n"
      operationId: regenerateCard
      security:
      - OAuth2:
        - read_write
      summary: Regenerate Card
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/setPIN:
    put:
      description: |
        Overwrite the Card PIN code.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: setPin
      security:
      - OAuth2:
        - read_write
      summary: Set Card PIN
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/UnblockPIN:
    put:
      description: |
        Unblock the Card PIN code.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: unblockPin
      security:
      - OAuth2:
        - read_write
      summary: Unblock Card PIN
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/unblockcvc2:
    put:
      description: |
        Unblock a Card whose CVC2 is locked.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: unblockCvc
      security:
      - OAuth2: []
      summary: Unblock Card CVC2
      tags:
      - Cards
      x-accepts:
      - application/json
  /v1/cards/{cardId}/authentication-methods:
    get:
      description: |
        Retrieve the authentication methods of a Card.
      operationId: getAuthMethods
      security:
      - OAuth2: []
      summary: Get Authentication Methods
      tags:
      - Card 3DSecure Enrollment (SCA)
      x-accepts:
      - application/json
    post:
      description: |
        Define the authentication method of a Card.
      operationId: postAuthMethods
      security:
      - OAuth2: []
      summary: Create Authenticaton Methods
      tags:
      - Card 3DSecure Enrollment (SCA)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/authentication-methods/{methodId}:
    delete:
      description: Delete the authentication method of a Card. Only available for
        OOB method.
      operationId: deleteAuthMethods
      security:
      - OAuth2: []
      summary: Delete Authentication Method
      tags:
      - Card 3DSecure Enrollment (SCA)
      x-accepts:
      - application/json
    get:
      description: Retrieve details regarding the authentication method of a Card.
      operationId: getAuthMethodsDetails
      security:
      - OAuth2: []
      summary: Get Authentication Method
      tags:
      - Card 3DSecure Enrollment (SCA)
      x-accepts:
      - application/json
  /v1/cards/{cardId}/renewalDetails:
    get:
      description: |
        Retrieve the Card `renewalType`.
      operationId: getRenewalDetails
      security:
      - OAuth2:
        - read_write
        - admin
        - legal
      summary: Get Renewal Details
      tags:
      - Cards
      x-accepts:
      - application/json
    put:
      description: |
        Update the Card `renewalType`.
      operationId: updateRenewalDetails
      security:
      - OAuth2:
        - read_write
        - admin
        - legal
      summary: Update Renewal Details
      tags:
      - Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cards/{cardId}/renew:
    put:
      description: |
        Renew a Card manually.
      operationId: putRenew
      security:
      - OAuth2:
        - read_write
        - admin
        - legal
      summary: Renew Card
      tags:
      - Cards
      x-accepts:
      - application/json
  /v1/{cardId}/digitalizedCards:
    get:
      description: |
        Retrieve the list of Digitized Cards for a given `cardId`.
      operationId: getDigitalized
      security:
      - OAuth2: []
      summary: Get Digitized Cards
      tags:
      - Digitized Cards
      x-accepts:
      - application/json
  /v1/digitalizedCard/{id}:
    delete:
      description: |
        Deactivate a payment Token.
      operationId: deleteDigitalized
      security:
      - OAuth2: []
      summary: Deactivate Payment Token
      tags:
      - Digitized Cards
      x-accepts:
      - application/json
    get:
      description: Retrieve a payment token.
      operationId: getPaymentToken
      security:
      - OAuth2: []
      summary: Get Payment Token
      tags:
      - Digitized Cards
      x-accepts:
      - application/json
    put:
      description: |
        Update the status of a payment Token.
      operationId: putDigitalized
      security:
      - OAuth2: []
      summary: Update Payment Token Status
      tags:
      - Digitized Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/cardtransactions:
    get:
      description: |
        Retrieve Card Transactions based at least on one of the following intputs: `cardId`, `paymentId`, `publicToken`, `walletId`. This is the preferred request for end user-oriented usage.
      operationId: readCardTransaction
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Card Transactions
      tags:
      - Card Transactions
      x-accepts:
      - application/json
  /v1/cardtransactions/{cardtransactionId}:
    get:
      description: Retrieve a Card Transaction based on its `id`.
      operationId: getCardtransaction
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Card Transaction
      tags:
      - Card Transactions
      x-accepts:
      - application/json
  /v1/countryRestrictionGroups:
    get:
      description: Retrieve country restriction groups that match search criteria.
      operationId: getCountryRestrictionGroups
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Country Restriction Groups
      tags:
      - Country Restriction Groups
      x-accepts:
      - application/json
    post:
      description: Create a new country restriction group.
      operationId: postCountryRestrictionGroup
      security:
      - OAuth2:
        - read_write
      summary: Create Country Restriction Group
      tags:
      - Country Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/countryRestrictionGroups/{id}:
    delete:
      description: Cancel a country restriction group.
      operationId: deleteCountryRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: Cancel Country Restriction Group
      tags:
      - Country Restriction Groups
      x-accepts:
      - application/json
    get:
      description: Retrive a Country Restriction Group based on its `id`.
      operationId: getCountryRestrictionGroupsId
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Country Restriction Group
      tags:
      - Country Restriction Groups
      x-accepts:
      - application/json
    put:
      description: Edit a country restriction group.
      operationId: putCountryRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: Update Country Restriction Group
      tags:
      - Country Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/documents:
    get:
      description: Retrieve Documents based on search criteria.
      operationId: getDocuments
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Documents
      tags:
      - User Documents
      x-accepts:
      - application/json
    post:
      description: Create a Document.
      operationId: createDocuments
      security:
      - OAuth2:
        - read_write
      summary: Create Document
      tags:
      - User Documents
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/documents/{documentId}:
    delete:
      description: Remove a document.
      operationId: deleteDocument
      security:
      - OAuth2:
        - read_write
      summary: Delete Document
      tags:
      - User Documents
      x-accepts:
      - application/json
    get:
      description: Retrieve a Document using its `id`.
      operationId: getDocument
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Document
      tags:
      - User Documents
      x-accepts:
      - application/json
    put:
      description: Change the `name` of a Document.
      operationId: putDocument
      security:
      - OAuth2:
        - read_write
      summary: Update Document
      tags:
      - User Documents
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/documents/{documentId}/download:
    get:
      description: |
        Retrieve a Document download URL. You may read [the dedicated documentation for this feature](/guide/user-verification/documents.html#download-documents).
      operationId: getDocumentDownloadUrl
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Document Download URL
      tags:
      - User Documents
      x-accepts:
      - application/json
  /v1/issuerInitiatedDigitizationDatas:
    post:
      description: |
        Create a new issuerInitiatedDigitizationData request

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: tavRequestPOST
      security:
      - OAuth2:
        - read_write
      summary: Request issuerInitiatedDigitizationData
      tags:
      - Digitized Cards
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mandates:
    get:
      description: Retrieve Mandates that match search criteria.
      operationId: getMandates
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Mandates
      tags:
      - Mandates
      x-accepts:
      - application/json
    post:
      description: |
        Create a new mandate.
      operationId: postMandates
      security:
      - OAuth2:
        - read_write
      summary: Create Mandate
      tags:
      - Mandates
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mandates/{mandateId}:
    delete:
      description: Change the Mandate status to `CANCELED`.
      operationId: deleteMandate
      security:
      - OAuth2:
        - read_write
      summary: Revoke Mandate
      tags:
      - Mandates
      x-accepts:
      - application/json
    get:
      description: Retrieve a Mandate based on its `id`.
      operationId: getMandate
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Mandate
      tags:
      - Mandates
      x-accepts:
      - application/json
  /v1/mccRestrictionGroups:
    get:
      description: |
        Retrieve MCC Restriction Groups that match search criteria.
      operationId: getMccRestrictionGroups
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search MCC Restriction Groups
      tags:
      - MCC Restriction Groups
      x-accepts:
      - application/json
    post:
      description: Create a new Merchant Category Code (MCC) restriction group.
      operationId: postMccRestrictionGroup
      security:
      - OAuth2:
        - read_write
      summary: Create MCC Restriction Group
      tags:
      - MCC Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mccRestrictionGroups/{id}:
    delete:
      description: Cancel a MCC restriction group.
      operationId: deleteMccRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: Cancel MCC Restriction Group
      tags:
      - MCC Restriction Groups
      x-accepts:
      - application/json
    get:
      description: Retrieve a MCC Group based on its `id`.
      operationId: getMccRestrictionGroupsId
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get MCC Restriction Group
      tags:
      - MCC Restriction Groups
      x-accepts:
      - application/json
    put:
      description: Edit a MCC Restriction group.
      operationId: putMccRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: Update MCC Restriction Group
      tags:
      - MCC Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/merchantIdRestrictionGroups:
    get:
      description: Retrieve Merchant ID Restriction Groups that match search criteria.
      operationId: getMerchantIdRestrictionGroup
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search MID Restriction Groups
      tags:
      - Merchant ID Restriction Groups
      x-accepts:
      - application/json
    post:
      description: Create a new Merchant ID restriction group.
      operationId: postMerchantIdRestrictionGroup
      security:
      - OAuth2:
        - read_write
      summary: Create MID Restriction Group
      tags:
      - Merchant ID Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/merchantIdRestrictionGroup/{id}:
    delete:
      description: Cancel a merchant id restriction group.
      operationId: deleteMerchantIdRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: Cancel MID Restriction Group
      tags:
      - Merchant ID Restriction Groups
      x-accepts:
      - application/json
    put:
      description: Deprecated
      operationId: putMerchantIdRestrictionGroups
      security:
      - OAuth2:
        - read_write
      summary: (DEPRECATED) Update MID Restriction Group
      tags:
      - Merchant ID Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/merchantIdRestrictionGroups/{id}/DeltaUpdate:
    put:
      description: Update the list of Merchant Ids for a MID Restriction Group.
      operationId: put-merchandidrestrictiongroups-deltaupdate
      security:
      - OAuth2:
        - read_write
      summary: Update MID Restriction Group
      tags:
      - Merchant ID Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/merchantIdRestrictionGroups/{id}/PresenceCheck:
    put:
      description: Check if Merchant IDs list for a restriction group.
      operationId: put-midrestrictiongroups
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Check the presence of merchants IDs list for a restriction group
      tags:
      - Merchant ID Restriction Groups
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/payins:
    get:
      description: Get payins that match search criteria.
      operationId: getPayins
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Payins
      tags:
      - Payins
      x-accepts:
      - application/json
    post:
      description: Create a new payin.
      operationId: postPayin
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Create Payin
      tags:
      - Payins
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/payins/{payinId}:
    delete:
      description: |
        Cancels a Payin. This endpoint is only available for:
        * [Check cashing](/guide/cheques/introduction.html), before the treatment center receives the check.
        * [SEPA Direct Debit emission](/guide/transfers/direct-debit.html#emitted-direct-debits-sdde), before Treezor processes it.
      operationId: deletePayin
      security:
      - OAuth2:
        - read_write
      summary: Delete Payin
      tags:
      - Payins
      x-accepts:
      - application/json
    get:
      description: Retrieve a payin by its id.
      operationId: getPayin
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Payin
      tags:
      - Payins
      x-accepts:
      - application/json
  /v1/payinrefunds:
    get:
      description: |
        Search for payin refunds. These can relate to [Acquiring](/guide/acquiring/legacy-v1.html#refunds) or [SEPA recalls](/guide/transfers/sepa-recalls.html).
      operationId: getPayinrefunds
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Payin Refunds
      tags:
      - Payin Refunds
      x-accepts:
      - application/json
  /v1/payinrefunds/{id}:
    get:
      description: Get a payin refund.
      operationId: getPayinrefund
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Payin Refund
      tags:
      - Payin Refunds
      x-accepts:
      - application/json
  /v1/payouts:
    get:
      description: |
        Retrieve Payouts that match search criteria. The request must contain at least one of the following inputs: `userId`, `walletId`.
      operationId: getPayouts
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Payouts
      tags:
      - Payouts
      x-accepts:
      - application/json
    post:
      description: |
        Create a new payout.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postPayout
      security:
      - OAuth2:
        - read_write
      summary: Create Payout
      tags:
      - Payouts
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/payouts/{payoutId}:
    delete:
      description: |
        Change payout status to `CANCELED`. A `VALIDATED` payout can't be canceled.
      operationId: deletePayout
      security:
      - OAuth2:
        - read_write
      summary: Cancel Payout
      tags:
      - Payouts
      x-accepts:
      - application/json
    get:
      description: Retrieve a given Payout.
      operationId: getPayout
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Payout
      tags:
      - Payouts
      x-accepts:
      - application/json
  /v1/payoutRefunds:
    post:
      description: "Create a Payout Refund. \nAs of today, this feature is only available\
        \ for [emitting SCTE Inst Recalls](/guide/transfers/sepa-recalls.html#emitting-scte-inst-recalls).\n\
        \nFor SCTE Recalls and SDDR Refunds, you need to [open a ticket](https://treezor.zendesk.com/hc/en-us/articles/4403978479634-How-to-create-a-Zendesk-ticket)\
        \ to request Payout Refund.\n"
      operationId: postPayoutRefund
      security:
      - OAuth2:
        - read_write
      summary: Create Payout Refund
      tags:
      - Payout Refunds
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/payoutRefunds/{payoutRefundId}:
    get:
      description: |
        Retrieve a given Payout Refund with its `id`.
      operationId: getPayoutRefund
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Payout Refund
      tags:
      - Payout Refunds
      x-accepts:
      - application/json
  /v1/recallRs:
    get:
      description: Retrieve recalls or RROs
      operationId: getRecallRs
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Recalls or RRO
      tags:
      - Recalls
      x-accepts:
      - application/json
  /v1/recallRs/{recallId}:
    get:
      description: Retrieve a given recall or RRO.
      operationId: getRecallR
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Recall or RRO
      tags:
      - Recalls
      x-accepts:
      - application/json
  /v1/recallRs/{recallId}/response:
    put:
      description: Respond to a Recall or a RRO.
      operationId: putRecallR
      security:
      - OAuth2:
        - read_write
      summary: Respond to Recall or RRO
      tags:
      - Recalls
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/recall-sct-inst/{sctInstId}/{recallId}:
    get:
      description: Retrieve an SCT Inst Recall.
      operationId: getRecallSctInst
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get SCT Inst Recall
      tags:
      - Recalls
      x-accepts:
      - application/json
  /v1/recall-sct-inst/{sctInstId}/{recallId}/response:
    put:
      description: Provide your decision following an SCT Inst Recall.
      operationId: putRecallSctInst
      security:
      - OAuth2:
        - read_write
      summary: Respond to SCT Inst Recall
      tags:
      - Recalls
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/taxResidences:
    get:
      description: Retrieve Tax Residences that match your search conditions.
      operationId: getTaxresidences
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Tax Residences
      tags:
      - User Tax Residences
      x-accepts:
      - '*/*'
      - application/json
    post:
      description: |
        Create a new Tax Residence.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postTaxresidence
      security:
      - OAuth2:
        - read_write
      summary: Create Tax Residence
      tags:
      - User Tax Residences
      x-content-type: application/json
      x-accepts:
      - '*/*'
      - application/json
  /v1/taxResidences/{taxResidenceId}:
    delete:
      description: Delete a residence that match id
      operationId: deleteTaxresidence
      security:
      - OAuth2:
        - read_write
      summary: Delete a residence
      tags:
      - User Tax Residences
      x-accepts:
      - '*/*'
      - application/json
    get:
      description: Retrieve a Tax Residence based on its `id`.
      operationId: getTaxresidence
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Tax Residence
      tags:
      - User Tax Residences
      x-accepts:
      - '*/*'
      - application/json
    put:
      description: |
        Modify an existing Tax Residence.

        This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putTaxresidence
      security:
      - OAuth2:
        - read_write
      summary: Update Tax Residence
      tags:
      - User Tax Residences
      x-content-type: application/json
      x-accepts:
      - '*/*'
      - application/json
  /v1/transactions:
    get:
      description: |
        Retrieve Transactions that match search criteria. The request must contain at least one of the following inputs: `walletId`, `transactionId`, `executionDate`, `valueDate`
      operationId: getTransactions
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Transactions
      tags:
      - Transactions
      x-accepts:
      - application/json
  /v1/transactions/{transactionId}:
    get:
      description: Retrieve a transaction.
      operationId: getTransaction
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Transaction
      tags:
      - Transactions
      x-accepts:
      - application/json
  /v1/transfers:
    get:
      description: |
        Retrieve the list of transfers for at least one of those inputs:
        `walletId`, `beneficiaryWalletId`, `userId`, `beneficiaryUserId`, `transferId`, `transferTag`
      operationId: getTransfers
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Transfers
      tags:
      - Transfers
      x-accepts:
      - application/json
    post:
      description: |
        Create a new Wallet-to-Wallet transfer.

        This endpoint requires per-session or per-operation [SCA](/guide/strong-customer-authentication/introduction.html) on if the `beneficiaryWalletId` belongs to the current User or not.
      operationId: postTransfers
      security:
      - OAuth2:
        - read_write
      summary: Create Transfer
      tags:
      - Transfers
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/transfers/{transferId}:
    delete:
      description: "Change status of the Transfer to `CANCELED`. \n\nOnly transfers\
        \ whose stauts is `PENDING` can be canceled.\n"
      operationId: deleteTransfer
      security:
      - OAuth2:
        - read_write
      summary: Cancel Transfer
      tags:
      - Transfers
      x-accepts:
      - application/json
    get:
      description: Retrieve a transfer using its `id`.
      operationId: getTransfer
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Transfer
      tags:
      - Transfers
      x-accepts:
      - application/json
  /v1/users:
    get:
      description: Retrieve Users matching your search criteria.
      operationId: getUsers
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Users
      tags:
      - Users
      x-accepts:
      - application/json
    post:
      description: |
        You may read [the dedicated documentation for this feature](/guide/users/introduction.html#creation)
      operationId: postUsers
      security:
      - OAuth2:
        - legal
        - admin
      summary: Create User
      tags:
      - Users
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/users/{userId}:
    delete:
      description: |
        Update the user Status to `CANCELED`. See the [Deletion](/guide/users/modifications.html#deletion) article for more information.
      operationId: deleteUser
      security:
      - OAuth2:
        - read_write
        - admin
      summary: Disable User
      tags:
      - Users
      x-accepts:
      - application/json
    get:
      description: Retrieve user's information for given user's `id`.
      operationId: getUser
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get User
      tags:
      - Users
      x-accepts:
      - application/json
    put:
      description: |
        Update information regarding the User.

        This endpoint may require per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putUser
      security:
      - OAuth2:
        - read_write
      summary: Update User
      tags:
      - Users
      x-content-type: application/json
      x-accepts:
      - application/json
      - applicationcjson
  /v1/users/{userId}/Kycreview:
    put:
      description: |
        Request a KYC review for a given user and its children to Treezor. Learn more in the [KYC Request](/guide/user-verification/kyc-request.html) article.
      operationId: putKycreview
      security:
      - OAuth2:
        - read_write
      summary: Request KYC Review
      tags:
      - User KYC Review
      x-accepts:
      - application/json
  /v1/users/{userId}/kycliveness:
    post:
      description: |
        Start the Live Verficiation process, whether it is KYC Liveness or Certified Video. You may read [the dedicated documentation for this feature](/guide/user-verification/live-verification.html).
      operationId: postKycliveness
      security:
      - OAuth2:
        - read_write
        - admin
      summary: Initiate Live Verification
      tags:
      - Verification Solutions (KYC)
      x-content-type: application/json
      x-accepts:
      - application/json
    put:
      description: |
        Retrieve the live verification results, and make them available to Treezor.
        You may read [the dedicated documentation for this feature](/guide/user-verification/live-verification.html)
      operationId: put-kyc-liveness
      security:
      - OAuth2:
        - read_write
        - admin
      summary: Retrieve and Upload Live Verification Result
      tags:
      - Verification Solutions (KYC)
      x-accepts:
      - '*/*'
      - application/json
  /v1/users/{userId}/qes:
    post:
      description: "Start the qualified electronic signature (QES) verification. \n"
      operationId: postKycqes
      security:
      - OAuth2:
        - read_write
        - admin
      summary: Initiate QES Verification
      tags:
      - Verification Solutions (KYC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/users/{userId}/videoconference:
    post:
      description: |
        Start the [Video conference verification](/guide/user-verification/videoconf.html) process.
      operationId: postKycVconf
      security:
      - OAuth2:
        - read_write
        - admin
      summary: Initiate Video Conference Verification
      tags:
      - Verification Solutions (KYC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/virtualibans:
    get:
      description: Retrieve virtual IBANs that match search criteria.
      operationId: getvirtualibans
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Virtual IBANs
      tags:
      - Virtual IBANs
      x-accepts:
      - application/json
    post:
      description: Create a new virtual IBAN associated with a given Wallet.
      operationId: postVirtualIban
      security:
      - OAuth2:
        - read_write
      summary: Create Virtual IBAN
      tags:
      - Virtual IBANs
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/virtualibans/{virtualIbanId}:
    get:
      description: Retrieve a Virtual IBAN based on its `id`.
      operationId: getvirtualiban
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Virtual IBAN
      tags:
      - Virtual IBANs
      x-accepts:
      - application/json
    put:
      description: Update a Virtual IBAN's information.
      operationId: putVirtualIban
      security:
      - OAuth2:
        - read_write
      summary: Update Virtual IBAN
      tags:
      - Virtual IBANs
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/wallets:
    get:
      description: |
        Retrieve Wallets that match your search conditions. The request must specify at least one of those fields: `walletId`, `userId`, or `walletTypeId`.
      operationId: getWallets
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Search Wallets
      tags:
      - Wallets
      x-accepts:
      - application/json
    post:
      description: |
        Create a new Wallet. This endpoint requires per-session [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postWallets
      security:
      - OAuth2:
        - read_write
      summary: Create Wallet
      tags:
      - Wallets
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/wallets/{walletId}:
    delete:
      description: Change the status of the Wallet to `CANCELED`. This action is irreversible.
      operationId: deleteWallet
      security:
      - OAuth2:
        - read_write
      summary: Delete Wallet
      tags:
      - Wallets
      x-content-type: application/json
      x-accepts:
      - application/json
    get:
      description: Retrieve a Wallet based on its `id`.
      operationId: getWallet
      security:
      - OAuth2:
        - read_only
      summary: Get Wallet
      tags:
      - Wallets
      x-accepts:
      - application/json
    put:
      description: Modifiy a Wallet information
      operationId: putWallet
      security:
      - OAuth2:
        - read_write
      summary: Update Wallet
      tags:
      - Wallets
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/payout-sddr:
    post:
      description: Simulate a received SEPA Direct Debit into one of your Wallet in
        Sandbox.
      operationId: SimulateSDDR
      security:
      - OAuth2:
        - admin
      summary: Simulate SDDR Core
      tags:
      - Payouts
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/payin-sct:
    post:
      description: Simulate the reception of a SEPA Credit Transfer into one of your
        Wallet in Sandbox.
      operationId: simulateSctReception
      security:
      - OAuth2:
        - admin
      summary: Simulate SCTR
      tags:
      - Payins
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/sct-inst/payin:
    post:
      description: Simulate the reception of an instantaneous SEPA Credit Transfer
        into one of your Wallet in Sandbox.
      operationId: simulateSctInstReception
      security:
      - OAuth2:
        - admin
      summary: Simulate SCTR Inst
      tags:
      - Payins
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/sct-inst/recall:
    post:
      description: Simulate a recall for an instantaneous SEPA Credit Transfer.
      operationId: simulateSctInstRecall
      security:
      - OAuth2:
        - admin
      summary: Simulate SCT Inst recall
      tags:
      - Recalls
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/acquiring/payin:
    post:
      description: Simulate operations resulting from the card acquisition feature.
      operationId: SimulateAcquiringPayin
      security:
      - OAuth2:
        - admin
      summary: Simulate Acquiring Payin
      tags:
      - Acquiring (Simulation)
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/operations:
    post:
      description: |
        Create fake operations for a given Wallet. This may prove useful to test [Account Statements](/guide/wallets/account-statements.html) for instance.
      operationId: simulateOperations
      security:
      - OAuth2:
        - admin
      summary: Simulate Operations
      tags:
      - Operations
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/cardtransactions:
    post:
      description: Simulate Card Transactions in Sandbox environment
      operationId: simulateCardTransactions
      security:
      - OAuth2:
        - admin
      summary: Simulate Card Transactions
      tags:
      - Card Transactions
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/rulesets:
    get:
      description: Retrieve all rulesets.
      operationId: get-rulesets
      security:
      - OAuth2: []
      summary: Get Rulesets
      tags:
      - Card Rulesets (MDC)
      x-accepts:
      - application/json
    post:
      description: Create a Ruleset.
      operationId: create-ruleset
      security:
      - OAuth2: []
      summary: Create Ruleset
      tags:
      - Card Rulesets (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/rulesets/{rulesetId}:
    delete:
      description: Disable a Ruleset.
      operationId: disable-ruleset
      security:
      - OAuth2: []
      summary: Disable Ruleset
      tags:
      - Card Rulesets (MDC)
      x-accepts:
      - application/json
    get:
      description: Retrieve a Ruleset with its `id`.
      operationId: get-ruleset
      security:
      - OAuth2: []
      summary: Get Ruleset
      tags:
      - Card Rulesets (MDC)
      x-accepts:
      - application/json
    put:
      description: Modify a Ruleset.
      operationId: put-ruleset
      security:
      - OAuth2: []
      summary: Update Ruleset
      tags:
      - Card Rulesets (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/{cardId}/rulesets:
    get:
      description: Get all rulesets assigned to a given card.
      operationId: get-ruleset-from-card
      security:
      - OAuth2: []
      summary: Retrieve Card Rulesets
      tags:
      - Card Rulesets (MDC)
      x-accepts:
      - application/json
    post:
      description: Assign rulesets to a given card.
      operationId: attach-ruleset-to-card
      security:
      - OAuth2: []
      summary: Assign Rulesets
      tags:
      - Card Rulesets (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/{cardId}/ruleset/{rulesetId}/factsBalance:
    get:
      description: Retrieve a ruleset virtual balance.
      operationId: getFactsBalance
      security:
      - OAuth2: []
      summary: Retrieve Ruleset virtual balance
      tags:
      - Card Rulesets (MDC)
      x-accepts:
      - application/json
  /v1/mdc/mccLists:
    get:
      description: |
        Retrieve all the Merchant Category Code Lists for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: getMdcMccLists
      summary: Get all MCC Lists
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
    post:
      description: |
        Create a list of Merchant Category Codes for the [Multi-Criteria Dynamic Card (MDC)](/guide/cards/transactions-rules-engine.html) feature.
      operationId: postMdcMccList
      security:
      - OAuth2: []
      summary: Create MCC List
      tags:
      - MCC Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/mccLists/{id}:
    delete:
      description: |
        Delete a Merchant Category Code List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: deleteMdcMccList
      summary: Delete MCC List
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
    get:
      description: |
        Retrieve a Merchant Category Code List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature based on its `id`.
      operationId: getMdcMccList
      summary: Get MCC List
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
    put:
      description: |
        Update a Merchant Category Code List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: updateMdcMccList
      summary: Update MCC List
      tags:
      - MCC Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/mccLists/{id}/codes:
    post:
      description: |
        Import MCC values asynchronously into a Merchant Category Code Lists for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: importMdcMccListCodes
      summary: Import MCCs
      tags:
      - MCC Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/mccLists/{id}/codes/{mcc}:
    delete:
      description: "Remove the MCC from the MCC List. If the code isn't in the list,\
        \ the API returns an HTTP 404 error."
      operationId: removeMdcMccListCode
      summary: Remove MCC from List
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
    get:
      description: "Check in the MCC is included in the MCC List. If not, the API\
        \ returns an HTTP 404 error."
      operationId: checkMdcMccListCode
      summary: Check MCC Presence
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
    put:
      description: Add the MCC in the Merchant Category Code list.
      operationId: addMdcMccListCode
      summary: Add MCC to MCC List
      tags:
      - MCC Lists (MDC)
      x-accepts:
      - application/json
  /v1/mdc/midLists:
    get:
      description: |
        Retrieve all the Merchant Id Lists for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: getMdcMidLists
      summary: Get all MID Lists
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
    post:
      description: |
        Create a list of Merchant Ids for the [Multi-Criteria Dynamic Card (MDC)](/guide/cards/transactions-rules-engine.html) feature.
      operationId: postMdcMidList
      summary: Create Merchant Id List
      tags:
      - MID Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/midLists/{id}:
    delete:
      description: |
        Delete a Merchant Id List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: deleteMdcMidList
      summary: Delete MerchantId List
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
    get:
      description: |
        Retrieve a Merchant Id List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature based on its `id`.
      operationId: getMidMccList
      summary: Get MID List
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
    put:
      description: |
        Update a Merchant Id List for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: updateMdcMidList
      summary: Update MerchantId List
      tags:
      - MID Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/midLists/{id}/merchantIds:
    post:
      description: |
        Import MCC values asynchronously into a Merchant Category Code Lists for the [Multi-Criteria Dynamic Card](/guide/cards/transactions-rules-engine.html) feature.
      operationId: importMdcMidListCodes
      summary: Import MIDs
      tags:
      - MID Lists (MDC)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/mdc/midLists/{id}/merchantIds/{mid}:
    delete:
      description: Remove the MID from the MID List.
      operationId: removeMdcMidListCode
      summary: Remove MCC from List
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
    get:
      description: Check in the MCC is included in the MCC List.
      operationId: checkMdcMidListCode
      summary: Check MID Presence
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
    put:
      description: Add the MID in the Merchant Id list.
      operationId: addMdcMidListCode
      summary: Add MID to MID List
      tags:
      - MID Lists (MDC)
      x-accepts:
      - application/json
  /v1/cardDigitalizations:
    get:
      deprecated: true
      description: Search for card digitalizations.
      operationId: readcardDigitalizations
      security:
      - OAuth2: []
      summary: Search Card Digitalizations
      tags:
      - Cards Digitalization
      x-accepts:
      - application/json
  /v1/cardDigitalizations/{id}:
    delete:
      deprecated: true
      description: Delete a payment Token
      operationId: deletecardDigitalizationsId
      security:
      - OAuth2: []
      summary: Delete Payment Token
      tags:
      - Cards Digitalization
      x-accepts:
      - application/json
    get:
      deprecated: true
      description: Retrieve a Card Digitalization based on its `id`.
      operationId: cardDigitalizationsId
      security:
      - OAuth2: []
      summary: Get Card Digitalization
      tags:
      - Cards Digitalization
      x-accepts:
      - application/json
    put:
      deprecated: true
      description: |
        Update the status of a payment Token

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: putcardDigitalizationsId
      security:
      - OAuth2: []
      summary: Update Payment Token Status
      tags:
      - Cards Digitalization
      x-accepts:
      - application/json
  /core-connect/scheduledPayment:
    get:
      description: Retrieve Scheduled Payment orders based on the corresponding `userId`
        and/or `walletId`
      operationId: getScheduledPayment
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Scheduled Payment
      tags:
      - Scheduled Payments
      x-accepts:
      - application/json
    post:
      description: |
        Schedule a Payout or a Wallet-to-Wallet transfer for a future date.

        This endpoint requires per-operation [SCA](/guide/strong-customer-authentication/introduction.html).
      operationId: postScheduledPayment
      security:
      - OAuth2:
        - read_write
      summary: Create Scheduled Payment
      tags:
      - Scheduled Payments
      x-content-type: application/json
      x-accepts:
      - application/json
  /core-connect/scheduledPayment/{scheduledPaymentId}:
    delete:
      description: Cancel a Scheduled Payment order
      operationId: deleteScheduledPayment
      security:
      - OAuth2:
        - read_write
      summary: Delete Scheduled Payment
      tags:
      - Scheduled Payments
      x-accepts:
      - application/json
  /core-connect/scheduledPayment/{scheduledPaymentId}/payments:
    get:
      description: Retrieve the list of executed payments for a given Scheduled Payment
        order
      operationId: getScheduledPaymentOperations
      security:
      - OAuth2:
        - read_only
        - read_write
      summary: Get Scheduled Payment Operations
      tags:
      - Scheduled Payments
      x-accepts:
      - application/json
  /v1/topups/cards/authorizations:
    post:
      description: |
        Create an authorization to make a card topup payin within 7 days. The card must be [tokenized](/guide/acquiring/card-tokenization.html) first.
      operationId: postAcqAuth
      security:
      - OAuth2:
        - read_write
      summary: Create Authorization
      tags:
      - Acquiring (Card Topups)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/topups/cards/authorizations/{authorizationUuid}:
    delete:
      description: Delete an authorization from the system
      operationId: deleteAcqAuth
      security:
      - OAuth2:
        - read_write
      summary: Delete Authorization
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
    get:
      description: Retrieve an authorization from the system.
      operationId: getAcqAuth
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Authorization
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
  /v1/topups/cards/authorizations/{authorizationUuid}/payins:
    get:
      description: List payins created from a given authorization.
      operationId: getAcqAuthPayins
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Authorization Payins
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
    post:
      description: "Create a payin from an authorization. The amount must be ≤ to\
        \ the authorization amount. [Learn more](/guide/acquiring/preauthorized.html#advanced-capture)."
      operationId: postAcqAuthPayin
      security:
      - OAuth2:
        - read_write
      summary: Create Payin from Authorization
      tags:
      - Acquiring (Card Topups)
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/topups/cards/notification/authorizations:
    post:
      description: |
        Mocks an HiPay authorization notification provided the minimal set of
        parameters to generate a refund notification.
      operationId: acquiringv2-topup-cards-simulation-notification-autorization
      security:
      - OAuth2:
        - admin
      summary: Simulate HiPay authorization notification
      tags:
      - Acquiring (Simulation)
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/topups/cards/notification/payins:
    post:
      description: |
        Mocks an HiPay payin notification providing the minimal set of
        parameters to generate a payin notification.
      operationId: acquiringv2-topup-cards-simulation-notification-payins
      security:
      - OAuth2:
        - admin
      summary: Simulate HiPay payin notification
      tags:
      - Acquiring (Simulation)
      x-content-type: application/x-www-form-urlencoded
      x-accepts:
      - application/json
  /simulation/topups/cards/notification/refunds:
    post:
      description: |
        Mocks an HiPay refund notification providing the minimal set of parameters to generate a refund notification.
      operationId: acquiringv2-topup-cards-simulation-notification-refunds
      security:
      - OAuth2:
        - admin
      summary: Simulate HiPay refund notification
      tags:
      - Acquiring (Simulation)
      x-content-type: application/json
      x-accepts:
      - application/json
  /simulation/topups/cards/notification/chargebacks:
    post:
      description: |
        Mocks an HiPay chargeback notification providing the minimal set of parameters to generate a chargeback notification.
      operationId: acquiringv2-topup-cards-simulation-notification-chargebacks
      security:
      - OAuth2:
        - admin
      summary: Simulate HiPay chargeback notification
      tags:
      - Acquiring (Simulation)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/topups/cards/refunds/{refundUuid}:
    get:
      description: Retrieve a card acquring refund from the system.
      operationId: acquiringv2-topup-cards-refunds-get
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Refund
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
  /v1/topups/cards/refunds:
    post:
      description: Create a new card topup refund.
      operationId: acquiringv2-topup-cards-refunds-post
      security:
      - OAuth2:
        - read_write
      summary: Create Refund
      tags:
      - Acquiring (Card Topups)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/topups/cards/chargebacks/{chargebackUuid}:
    get:
      description: Retrieve a card acquiring a chargeback from the system.
      operationId: acquiringv2-topup-cards-chargebacks-get
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Chargeback
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
  /v1/topups/cards/users/{userId}/topupCards:
    get:
      description: Get topup cards.
      operationId: getTopupCards
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Search Topup Cards
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
    post:
      description: |
        Create a new topup card. The card must have been previously tokenized.
      operationId: postTopupCard
      security:
      - OAuth2:
        - read_write
      summary: Create Topup Card
      tags:
      - Acquiring (Card Topups)
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/topups/cards/users/{userId}/topupCards/{topupCardId}:
    delete:
      description: Change topup card status to CANCELED.
      operationId: deleteTopupCard
      security:
      - OAuth2:
        - read_write
      summary: Cancel Topup Card
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
    get:
      description: Retrieve the details of a Topup Card.
      operationId: getTopupCard
      security:
      - OAuth2:
        - read_write
        - read_only
      summary: Get Topup Card
      tags:
      - Acquiring (Card Topups)
      x-accepts:
      - application/json
components:
  securitySchemes:
    OAuth2:
      description: |
        The Treezor API is secured by a JWT provided by Treezor, with OAuth2 client credentials flow.
        The token can be used in the `Authorization` header as `Bearer <token>`.
      flows:
        clientCredentials:
          refreshUrl: https://your-company-name.sandbox.treezor.co/oauth/token
          scopes:
            read_only: "Access for GET endpoints (except legal, admin)"
            read_write: "Access for PUT|POST|DELETE endpoints (except legal, admin)"
            admin: Access for API configuration-related endpoints
            legal: "Access for sensitive endpoints (e.g., KYC, users, documents)"
            support_user_management: Access for support users-related endpoints
          tokenUrl: https://your-company-name.sandbox.treezor.co/oauth/token
      type: oauth2

